// Code generated by ogen, DO NOT EDIT.

package api

// Hash computes a hash value for WorkflowTransition using FNV-1a.
// Equal objects must produce equal hashes.
func (a WorkflowTransition) Hash() uint64 {
	_ = "STUB: not implemented"

	// Hash primitive field: ID
	return 0
}

// Hash primitive field: Name

// Hash optional field: FromStatusId

// Hash optional field: ToStatusId

// Hash optional field: Conditions
