// Code generated by ogen, DO NOT EDIT.

package api

// Hash computes a hash value for RuleConfiguration using FNV-1a.
// Equal objects must produce equal hashes.
func (a RuleConfiguration) Hash() uint64 {
	_ = "STUB: not implemented"

	// Hash optional field: RuleKey
	return 0
}

// Hash optional field: ParameterGroup
