// Code generated by ogen, DO NOT EDIT.

package api

// Equal compares two Condition instances for equality.
// The depth parameter prevents infinite recursion on nested objects.
func (a Condition) Equal(b Condition, depth int) bool { _ = "STUB: not implemented"; return false }

// Compare optional field: Type

// Compare optional field: Negated

// Compare optional field: Configuration
