// Code generated by ogen, DO NOT EDIT.

package api

func (s *AddStickerToSet) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *Animation) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *AnswerCallbackQuery) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *AnswerInlineQuery) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *AnswerShippingQuery) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *Audio) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *BotCommand) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *CallbackQuery) Validate() error { _ = "STUB: not implemented"; return nil }

// optional

func (s *Chat) Validate() error { _ = "STUB: not implemented"; return nil }

// optional

func (s *ChatInviteLink) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *ChatJoinRequest) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *ChatLocation) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *ChatMemberUpdated) Validate() error { _ = "STUB: not implemented"; return nil }

func (s ChatType) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *ChosenInlineResult) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *CopyMessage) Validate() error { _ = "STUB: not implemented"; return nil }

func (s CopyMessageReplyMarkup) Validate() error { _ = "STUB: not implemented"; return nil }

// no validation needed

func (s *CreateChatInviteLink) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *CreateNewStickerSet) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *Document) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *EditChatInviteLink) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *EditMessageCaption) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *EditMessageLiveLocation) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *EditMessageMedia) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *EditMessageReplyMarkup) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *EditMessageText) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *EncryptedPassportElement) Validate() error { _ = "STUB: not implemented"; return nil }

func (s EncryptedPassportElementType) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *ForceReply) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *Game) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *GetUpdates) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *GetUserProfilePhotos) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InlineKeyboardButton) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InlineKeyboardMarkup) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InlineQuery) Validate() error { _ = "STUB: not implemented"; return nil }

func (s InlineQueryChatType) Validate() error { _ = "STUB: not implemented"; return nil }

func (s InlineQueryResult) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InlineQueryResultArticle) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InlineQueryResultAudio) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InlineQueryResultCachedAudio) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InlineQueryResultCachedDocument) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InlineQueryResultCachedGif) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InlineQueryResultCachedMpeg4Gif) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InlineQueryResultCachedPhoto) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InlineQueryResultCachedSticker) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InlineQueryResultCachedVideo) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InlineQueryResultCachedVoice) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InlineQueryResultContact) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InlineQueryResultDocument) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InlineQueryResultGame) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InlineQueryResultGif) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InlineQueryResultLocation) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InlineQueryResultMpeg4Gif) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InlineQueryResultPhoto) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InlineQueryResultVenue) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InlineQueryResultVideo) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InlineQueryResultVoice) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InputContactMessageContent) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InputInvoiceMessageContent) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InputLocationMessageContent) Validate() error { _ = "STUB: not implemented"; return nil }

func (s InputMedia) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InputMediaAnimation) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InputMediaAudio) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InputMediaDocument) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InputMediaPhoto) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InputMediaVideo) Validate() error { _ = "STUB: not implemented"; return nil }

func (s InputMessageContent) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InputTextMessageContent) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *InputVenueMessageContent) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *Location) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *MaskPosition) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *Message) Validate() error { _ = "STUB: not implemented"; return nil }

// optional

// optional

func (s *MessageEntity) Validate() error { _ = "STUB: not implemented"; return nil }

func (s MessageEntityType) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PassportData) Validate() error { _ = "STUB: not implemented"; return nil }

func (s PassportElementError) Validate() error { _ = "STUB: not implemented"; return nil }

// no validation needed

func (s *PassportElementErrorDataField) Validate() error { _ = "STUB: not implemented"; return nil }

func (s PassportElementErrorDataFieldType) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PassportElementErrorFile) Validate() error { _ = "STUB: not implemented"; return nil }

func (s PassportElementErrorFileType) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PassportElementErrorFiles) Validate() error { _ = "STUB: not implemented"; return nil }

func (s PassportElementErrorFilesType) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PassportElementErrorFrontSide) Validate() error { _ = "STUB: not implemented"; return nil }

func (s PassportElementErrorFrontSideType) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PassportElementErrorReverseSide) Validate() error { _ = "STUB: not implemented"; return nil }

func (s PassportElementErrorReverseSideType) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PassportElementErrorSelfie) Validate() error { _ = "STUB: not implemented"; return nil }

func (s PassportElementErrorSelfieType) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PassportElementErrorTranslationFile) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s PassportElementErrorTranslationFileType) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PassportElementErrorTranslationFiles) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s PassportElementErrorTranslationFilesType) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PhotoSize) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *Poll) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PollAnswer) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PollOption) Validate() error { _ = "STUB: not implemented"; return nil }

func (s PollType) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *ReplyKeyboardMarkup) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *ResultArrayOfBotCommand) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *ResultArrayOfMessage) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *ResultArrayOfUpdate) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *ResultChat) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *ResultChatInviteLink) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *ResultMessage) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *ResultPoll) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *ResultUserProfilePhotos) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *SendAnimation) Validate() error { _ = "STUB: not implemented"; return nil }

func (s SendAnimationReplyMarkup) Validate() error { _ = "STUB: not implemented"; return nil }

// no validation needed

func (s *SendAudio) Validate() error { _ = "STUB: not implemented"; return nil }

func (s SendAudioReplyMarkup) Validate() error { _ = "STUB: not implemented"; return nil }

// no validation needed

func (s *SendContact) Validate() error { _ = "STUB: not implemented"; return nil }

func (s SendContactReplyMarkup) Validate() error { _ = "STUB: not implemented"; return nil }

// no validation needed

func (s *SendDice) Validate() error { _ = "STUB: not implemented"; return nil }

func (s SendDiceReplyMarkup) Validate() error { _ = "STUB: not implemented"; return nil }

// no validation needed

func (s *SendDocument) Validate() error { _ = "STUB: not implemented"; return nil }

func (s SendDocumentReplyMarkup) Validate() error { _ = "STUB: not implemented"; return nil }

// no validation needed

func (s *SendGame) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *SendInvoice) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *SendLocation) Validate() error { _ = "STUB: not implemented"; return nil }

func (s SendLocationReplyMarkup) Validate() error { _ = "STUB: not implemented"; return nil }

// no validation needed

func (s *SendMediaGroup) Validate() error { _ = "STUB: not implemented"; return nil }

func (s SendMediaGroupMediaItem) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *SendMessage) Validate() error { _ = "STUB: not implemented"; return nil }

func (s SendMessageReplyMarkup) Validate() error { _ = "STUB: not implemented"; return nil }

// no validation needed

func (s *SendPhoto) Validate() error { _ = "STUB: not implemented"; return nil }

func (s SendPhotoReplyMarkup) Validate() error { _ = "STUB: not implemented"; return nil }

// no validation needed

func (s *SendPoll) Validate() error { _ = "STUB: not implemented"; return nil }

func (s SendPollReplyMarkup) Validate() error { _ = "STUB: not implemented"; return nil }

// no validation needed

func (s *SendSticker) Validate() error { _ = "STUB: not implemented"; return nil }

func (s SendStickerReplyMarkup) Validate() error { _ = "STUB: not implemented"; return nil }

// no validation needed

func (s *SendVenue) Validate() error { _ = "STUB: not implemented"; return nil }

func (s SendVenueReplyMarkup) Validate() error { _ = "STUB: not implemented"; return nil }

// no validation needed

func (s *SendVideo) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *SendVideoNote) Validate() error { _ = "STUB: not implemented"; return nil }

func (s SendVideoNoteReplyMarkup) Validate() error { _ = "STUB: not implemented"; return nil }

// no validation needed

func (s SendVideoReplyMarkup) Validate() error { _ = "STUB: not implemented"; return nil }

// no validation needed

func (s *SendVoice) Validate() error { _ = "STUB: not implemented"; return nil }

func (s SendVoiceReplyMarkup) Validate() error { _ = "STUB: not implemented"; return nil }

// no validation needed

func (s *SetChatAdministratorCustomTitle) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *SetChatDescription) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *SetChatTitle) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *SetMyCommands) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *SetPassportDataErrors) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *ShippingOption) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *Sticker) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *StopMessageLiveLocation) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *StopPoll) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *Update) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *UserProfilePhotos) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *Venue) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *Video) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *VideoNote) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *Voice) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *VoiceChatEnded) Validate() error { _ = "STUB: not implemented"; return nil }
