// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
)

type codeRecorder struct {
	http.ResponseWriter
	status int
}

func (c *codeRecorder) WriteHeader(status int) { _ = "STUB: not implemented"; return }

func (c *codeRecorder) Unwrap() http.ResponseWriter {
	_ = "STUB: not implemented"
	return *

	// handleAddStickerToSetRequest handles addStickerToSet operation.
	//
	// POST /addStickerToSet
	new(http.ResponseWriter)
}

func (s *Server) handleAddStickerToSetRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleAnswerCallbackQueryRequest handles answerCallbackQuery operation.
//
// POST /answerCallbackQuery
func (s *Server) handleAnswerCallbackQueryRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleAnswerInlineQueryRequest handles answerInlineQuery operation.
//
// POST /answerInlineQuery
func (s *Server) handleAnswerInlineQueryRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleAnswerPreCheckoutQueryRequest handles answerPreCheckoutQuery operation.
//
// POST /answerPreCheckoutQuery
func (s *Server) handleAnswerPreCheckoutQueryRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleAnswerShippingQueryRequest handles answerShippingQuery operation.
//
// POST /answerShippingQuery
func (s *Server) handleAnswerShippingQueryRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleApproveChatJoinRequestRequest handles approveChatJoinRequest operation.
//
// POST /approveChatJoinRequest
func (s *Server) handleApproveChatJoinRequestRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleBanChatMemberRequest handles banChatMember operation.
//
// POST /banChatMember
func (s *Server) handleBanChatMemberRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleBanChatSenderChatRequest handles banChatSenderChat operation.
//
// POST /banChatSenderChat
func (s *Server) handleBanChatSenderChatRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleCloseRequest handles close operation.
//
// POST /close
func (s *Server) handleCloseRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleCopyMessageRequest handles copyMessage operation.
//
// POST /copyMessage
func (s *Server) handleCopyMessageRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleCreateChatInviteLinkRequest handles createChatInviteLink operation.
//
// POST /createChatInviteLink
func (s *Server) handleCreateChatInviteLinkRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleCreateNewStickerSetRequest handles createNewStickerSet operation.
//
// POST /createNewStickerSet
func (s *Server) handleCreateNewStickerSetRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleDeclineChatJoinRequestRequest handles declineChatJoinRequest operation.
//
// POST /declineChatJoinRequest
func (s *Server) handleDeclineChatJoinRequestRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleDeleteChatPhotoRequest handles deleteChatPhoto operation.
//
// POST /deleteChatPhoto
func (s *Server) handleDeleteChatPhotoRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleDeleteChatStickerSetRequest handles deleteChatStickerSet operation.
//
// POST /deleteChatStickerSet
func (s *Server) handleDeleteChatStickerSetRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleDeleteMessageRequest handles deleteMessage operation.
//
// POST /deleteMessage
func (s *Server) handleDeleteMessageRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleDeleteMyCommandsRequest handles deleteMyCommands operation.
//
// POST /deleteMyCommands
func (s *Server) handleDeleteMyCommandsRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleDeleteStickerFromSetRequest handles deleteStickerFromSet operation.
//
// POST /deleteStickerFromSet
func (s *Server) handleDeleteStickerFromSetRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleDeleteWebhookRequest handles deleteWebhook operation.
//
// POST /deleteWebhook
func (s *Server) handleDeleteWebhookRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleEditChatInviteLinkRequest handles editChatInviteLink operation.
//
// POST /editChatInviteLink
func (s *Server) handleEditChatInviteLinkRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleEditMessageCaptionRequest handles editMessageCaption operation.
//
// POST /editMessageCaption
func (s *Server) handleEditMessageCaptionRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleEditMessageLiveLocationRequest handles editMessageLiveLocation operation.
//
// POST /editMessageLiveLocation
func (s *Server) handleEditMessageLiveLocationRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleEditMessageMediaRequest handles editMessageMedia operation.
//
// POST /editMessageMedia
func (s *Server) handleEditMessageMediaRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleEditMessageReplyMarkupRequest handles editMessageReplyMarkup operation.
//
// POST /editMessageReplyMarkup
func (s *Server) handleEditMessageReplyMarkupRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleEditMessageTextRequest handles editMessageText operation.
//
// POST /editMessageText
func (s *Server) handleEditMessageTextRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleExportChatInviteLinkRequest handles exportChatInviteLink operation.
//
// POST /exportChatInviteLink
func (s *Server) handleExportChatInviteLinkRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleForwardMessageRequest handles forwardMessage operation.
//
// POST /forwardMessage
func (s *Server) handleForwardMessageRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleGetChatRequest handles getChat operation.
//
// POST /getChat
func (s *Server) handleGetChatRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleGetChatAdministratorsRequest handles getChatAdministrators operation.
//
// POST /getChatAdministrators
func (s *Server) handleGetChatAdministratorsRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleGetChatMemberRequest handles getChatMember operation.
//
// POST /getChatMember
func (s *Server) handleGetChatMemberRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleGetChatMemberCountRequest handles getChatMemberCount operation.
//
// POST /getChatMemberCount
func (s *Server) handleGetChatMemberCountRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleGetFileRequest handles getFile operation.
//
// POST /getFile
func (s *Server) handleGetFileRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleGetGameHighScoresRequest handles getGameHighScores operation.
//
// POST /getGameHighScores
func (s *Server) handleGetGameHighScoresRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleGetMeRequest handles getMe operation.
//
// POST /getMe
func (s *Server) handleGetMeRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleGetMyCommandsRequest handles getMyCommands operation.
//
// POST /getMyCommands
func (s *Server) handleGetMyCommandsRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleGetStickerSetRequest handles getStickerSet operation.
//
// POST /getStickerSet
func (s *Server) handleGetStickerSetRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleGetUpdatesRequest handles getUpdates operation.
//
// POST /getUpdates
func (s *Server) handleGetUpdatesRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleGetUserProfilePhotosRequest handles getUserProfilePhotos operation.
//
// POST /getUserProfilePhotos
func (s *Server) handleGetUserProfilePhotosRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleGetWebhookInfoRequest handles getWebhookInfo operation.
//
// POST /getWebhookInfo
func (s *Server) handleGetWebhookInfoRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleLeaveChatRequest handles leaveChat operation.
//
// POST /leaveChat
func (s *Server) handleLeaveChatRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleLogOutRequest handles logOut operation.
//
// POST /logOut
func (s *Server) handleLogOutRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handlePinChatMessageRequest handles pinChatMessage operation.
//
// POST /pinChatMessage
func (s *Server) handlePinChatMessageRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handlePromoteChatMemberRequest handles promoteChatMember operation.
//
// POST /promoteChatMember
func (s *Server) handlePromoteChatMemberRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleRestrictChatMemberRequest handles restrictChatMember operation.
//
// POST /restrictChatMember
func (s *Server) handleRestrictChatMemberRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleRevokeChatInviteLinkRequest handles revokeChatInviteLink operation.
//
// POST /revokeChatInviteLink
func (s *Server) handleRevokeChatInviteLinkRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSendAnimationRequest handles sendAnimation operation.
//
// POST /sendAnimation
func (s *Server) handleSendAnimationRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSendAudioRequest handles sendAudio operation.
//
// POST /sendAudio
func (s *Server) handleSendAudioRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSendChatActionRequest handles sendChatAction operation.
//
// POST /sendChatAction
func (s *Server) handleSendChatActionRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSendContactRequest handles sendContact operation.
//
// POST /sendContact
func (s *Server) handleSendContactRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSendDiceRequest handles sendDice operation.
//
// POST /sendDice
func (s *Server) handleSendDiceRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSendDocumentRequest handles sendDocument operation.
//
// POST /sendDocument
func (s *Server) handleSendDocumentRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSendGameRequest handles sendGame operation.
//
// POST /sendGame
func (s *Server) handleSendGameRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSendInvoiceRequest handles sendInvoice operation.
//
// POST /sendInvoice
func (s *Server) handleSendInvoiceRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSendLocationRequest handles sendLocation operation.
//
// POST /sendLocation
func (s *Server) handleSendLocationRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSendMediaGroupRequest handles sendMediaGroup operation.
//
// POST /sendMediaGroup
func (s *Server) handleSendMediaGroupRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSendMessageRequest handles sendMessage operation.
//
// POST /sendMessage
func (s *Server) handleSendMessageRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSendPhotoRequest handles sendPhoto operation.
//
// POST /sendPhoto
func (s *Server) handleSendPhotoRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSendPollRequest handles sendPoll operation.
//
// POST /sendPoll
func (s *Server) handleSendPollRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSendStickerRequest handles sendSticker operation.
//
// POST /sendSticker
func (s *Server) handleSendStickerRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSendVenueRequest handles sendVenue operation.
//
// POST /sendVenue
func (s *Server) handleSendVenueRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSendVideoRequest handles sendVideo operation.
//
// POST /sendVideo
func (s *Server) handleSendVideoRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSendVideoNoteRequest handles sendVideoNote operation.
//
// POST /sendVideoNote
func (s *Server) handleSendVideoNoteRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSendVoiceRequest handles sendVoice operation.
//
// POST /sendVoice
func (s *Server) handleSendVoiceRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSetChatAdministratorCustomTitleRequest handles setChatAdministratorCustomTitle operation.
//
// POST /setChatAdministratorCustomTitle
func (s *Server) handleSetChatAdministratorCustomTitleRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSetChatDescriptionRequest handles setChatDescription operation.
//
// POST /setChatDescription
func (s *Server) handleSetChatDescriptionRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSetChatPermissionsRequest handles setChatPermissions operation.
//
// POST /setChatPermissions
func (s *Server) handleSetChatPermissionsRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSetChatPhotoRequest handles setChatPhoto operation.
//
// POST /setChatPhoto
func (s *Server) handleSetChatPhotoRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSetChatStickerSetRequest handles setChatStickerSet operation.
//
// POST /setChatStickerSet
func (s *Server) handleSetChatStickerSetRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSetChatTitleRequest handles setChatTitle operation.
//
// POST /setChatTitle
func (s *Server) handleSetChatTitleRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSetGameScoreRequest handles setGameScore operation.
//
// POST /setGameScore
func (s *Server) handleSetGameScoreRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSetMyCommandsRequest handles setMyCommands operation.
//
// POST /setMyCommands
func (s *Server) handleSetMyCommandsRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSetPassportDataErrorsRequest handles setPassportDataErrors operation.
//
// POST /setPassportDataErrors
func (s *Server) handleSetPassportDataErrorsRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSetStickerPositionInSetRequest handles setStickerPositionInSet operation.
//
// POST /setStickerPositionInSet
func (s *Server) handleSetStickerPositionInSetRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSetStickerSetThumbRequest handles setStickerSetThumb operation.
//
// POST /setStickerSetThumb
func (s *Server) handleSetStickerSetThumbRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleSetWebhookRequest handles setWebhook operation.
//
// POST /setWebhook
func (s *Server) handleSetWebhookRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleStopMessageLiveLocationRequest handles stopMessageLiveLocation operation.
//
// POST /stopMessageLiveLocation
func (s *Server) handleStopMessageLiveLocationRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleStopPollRequest handles stopPoll operation.
//
// POST /stopPoll
func (s *Server) handleStopPollRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleUnbanChatMemberRequest handles unbanChatMember operation.
//
// POST /unbanChatMember
func (s *Server) handleUnbanChatMemberRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleUnbanChatSenderChatRequest handles unbanChatSenderChat operation.
//
// POST /unbanChatSenderChat
func (s *Server) handleUnbanChatSenderChatRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleUnpinAllChatMessagesRequest handles unpinAllChatMessages operation.
//
// POST /unpinAllChatMessages
func (s *Server) handleUnpinAllChatMessagesRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleUnpinChatMessageRequest handles unpinChatMessage operation.
//
// POST /unpinChatMessage
func (s *Server) handleUnpinChatMessageRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleUploadStickerFileRequest handles uploadStickerFile operation.
//
// POST /uploadStickerFile
func (s *Server) handleUploadStickerFileRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.
