// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
)

func encodePatchAdmissionregistrationV1MutatingWebhookConfigurationRequest(
	req PatchAdmissionregistrationV1MutatingWebhookConfigurationReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchAdmissionregistrationV1ValidatingWebhookConfigurationRequest(
	req PatchAdmissionregistrationV1ValidatingWebhookConfigurationReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchApiextensionsV1CustomResourceDefinitionRequest(
	req PatchApiextensionsV1CustomResourceDefinitionReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchApiextensionsV1CustomResourceDefinitionStatusRequest(
	req PatchApiextensionsV1CustomResourceDefinitionStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchApiregistrationV1APIServiceRequest(
	req PatchApiregistrationV1APIServiceReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchApiregistrationV1APIServiceStatusRequest(
	req PatchApiregistrationV1APIServiceStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchAppsV1NamespacedControllerRevisionRequest(
	req PatchAppsV1NamespacedControllerRevisionReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchAppsV1NamespacedDaemonSetRequest(
	req PatchAppsV1NamespacedDaemonSetReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchAppsV1NamespacedDaemonSetStatusRequest(
	req PatchAppsV1NamespacedDaemonSetStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchAppsV1NamespacedDeploymentRequest(
	req PatchAppsV1NamespacedDeploymentReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchAppsV1NamespacedDeploymentScaleRequest(
	req PatchAppsV1NamespacedDeploymentScaleReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchAppsV1NamespacedDeploymentStatusRequest(
	req PatchAppsV1NamespacedDeploymentStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchAppsV1NamespacedReplicaSetRequest(
	req PatchAppsV1NamespacedReplicaSetReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchAppsV1NamespacedReplicaSetScaleRequest(
	req PatchAppsV1NamespacedReplicaSetScaleReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchAppsV1NamespacedReplicaSetStatusRequest(
	req PatchAppsV1NamespacedReplicaSetStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchAppsV1NamespacedStatefulSetRequest(
	req PatchAppsV1NamespacedStatefulSetReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchAppsV1NamespacedStatefulSetScaleRequest(
	req PatchAppsV1NamespacedStatefulSetScaleReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchAppsV1NamespacedStatefulSetStatusRequest(
	req PatchAppsV1NamespacedStatefulSetStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchAutoscalingV1NamespacedHorizontalPodAutoscalerRequest(
	req PatchAutoscalingV1NamespacedHorizontalPodAutoscalerReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchAutoscalingV1NamespacedHorizontalPodAutoscalerStatusRequest(
	req PatchAutoscalingV1NamespacedHorizontalPodAutoscalerStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerRequest(
	req PatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerStatusRequest(
	req PatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchAutoscalingV2beta2NamespacedHorizontalPodAutoscalerRequest(
	req PatchAutoscalingV2beta2NamespacedHorizontalPodAutoscalerReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchAutoscalingV2beta2NamespacedHorizontalPodAutoscalerStatusRequest(
	req PatchAutoscalingV2beta2NamespacedHorizontalPodAutoscalerStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchBatchV1NamespacedCronJobRequest(
	req PatchBatchV1NamespacedCronJobReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchBatchV1NamespacedCronJobStatusRequest(
	req PatchBatchV1NamespacedCronJobStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchBatchV1NamespacedJobRequest(
	req PatchBatchV1NamespacedJobReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchBatchV1NamespacedJobStatusRequest(
	req PatchBatchV1NamespacedJobStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchBatchV1beta1NamespacedCronJobRequest(
	req PatchBatchV1beta1NamespacedCronJobReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchBatchV1beta1NamespacedCronJobStatusRequest(
	req PatchBatchV1beta1NamespacedCronJobStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCertificatesV1CertificateSigningRequestRequest(
	req PatchCertificatesV1CertificateSigningRequestReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCertificatesV1CertificateSigningRequestApprovalRequest(
	req PatchCertificatesV1CertificateSigningRequestApprovalReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCertificatesV1CertificateSigningRequestStatusRequest(
	req PatchCertificatesV1CertificateSigningRequestStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCoordinationV1NamespacedLeaseRequest(
	req PatchCoordinationV1NamespacedLeaseReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCoreV1NamespaceRequest(
	req PatchCoreV1NamespaceReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCoreV1NamespaceStatusRequest(
	req PatchCoreV1NamespaceStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCoreV1NamespacedConfigMapRequest(
	req PatchCoreV1NamespacedConfigMapReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCoreV1NamespacedEndpointsRequest(
	req PatchCoreV1NamespacedEndpointsReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCoreV1NamespacedEventRequest(
	req PatchCoreV1NamespacedEventReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCoreV1NamespacedLimitRangeRequest(
	req PatchCoreV1NamespacedLimitRangeReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCoreV1NamespacedPersistentVolumeClaimRequest(
	req PatchCoreV1NamespacedPersistentVolumeClaimReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCoreV1NamespacedPersistentVolumeClaimStatusRequest(
	req PatchCoreV1NamespacedPersistentVolumeClaimStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCoreV1NamespacedPodRequest(
	req PatchCoreV1NamespacedPodReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCoreV1NamespacedPodEphemeralcontainersRequest(
	req PatchCoreV1NamespacedPodEphemeralcontainersReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCoreV1NamespacedPodStatusRequest(
	req PatchCoreV1NamespacedPodStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCoreV1NamespacedPodTemplateRequest(
	req PatchCoreV1NamespacedPodTemplateReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCoreV1NamespacedReplicationControllerRequest(
	req PatchCoreV1NamespacedReplicationControllerReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCoreV1NamespacedReplicationControllerScaleRequest(
	req PatchCoreV1NamespacedReplicationControllerScaleReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCoreV1NamespacedReplicationControllerStatusRequest(
	req PatchCoreV1NamespacedReplicationControllerStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCoreV1NamespacedResourceQuotaRequest(
	req PatchCoreV1NamespacedResourceQuotaReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCoreV1NamespacedResourceQuotaStatusRequest(
	req PatchCoreV1NamespacedResourceQuotaStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCoreV1NamespacedSecretRequest(
	req PatchCoreV1NamespacedSecretReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCoreV1NamespacedServiceRequest(
	req PatchCoreV1NamespacedServiceReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCoreV1NamespacedServiceAccountRequest(
	req PatchCoreV1NamespacedServiceAccountReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCoreV1NamespacedServiceStatusRequest(
	req PatchCoreV1NamespacedServiceStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCoreV1NodeRequest(
	req PatchCoreV1NodeReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCoreV1NodeStatusRequest(
	req PatchCoreV1NodeStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCoreV1PersistentVolumeRequest(
	req PatchCoreV1PersistentVolumeReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchCoreV1PersistentVolumeStatusRequest(
	req PatchCoreV1PersistentVolumeStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchDiscoveryV1NamespacedEndpointSliceRequest(
	req PatchDiscoveryV1NamespacedEndpointSliceReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchDiscoveryV1beta1NamespacedEndpointSliceRequest(
	req PatchDiscoveryV1beta1NamespacedEndpointSliceReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchEventsV1NamespacedEventRequest(
	req PatchEventsV1NamespacedEventReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchEventsV1beta1NamespacedEventRequest(
	req PatchEventsV1beta1NamespacedEventReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchFlowcontrolApiserverV1beta1FlowSchemaRequest(
	req PatchFlowcontrolApiserverV1beta1FlowSchemaReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchFlowcontrolApiserverV1beta1FlowSchemaStatusRequest(
	req PatchFlowcontrolApiserverV1beta1FlowSchemaStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchFlowcontrolApiserverV1beta1PriorityLevelConfigurationRequest(
	req PatchFlowcontrolApiserverV1beta1PriorityLevelConfigurationReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchFlowcontrolApiserverV1beta1PriorityLevelConfigurationStatusRequest(
	req PatchFlowcontrolApiserverV1beta1PriorityLevelConfigurationStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchFlowcontrolApiserverV1beta2FlowSchemaRequest(
	req PatchFlowcontrolApiserverV1beta2FlowSchemaReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchFlowcontrolApiserverV1beta2FlowSchemaStatusRequest(
	req PatchFlowcontrolApiserverV1beta2FlowSchemaStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchFlowcontrolApiserverV1beta2PriorityLevelConfigurationRequest(
	req PatchFlowcontrolApiserverV1beta2PriorityLevelConfigurationReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchFlowcontrolApiserverV1beta2PriorityLevelConfigurationStatusRequest(
	req PatchFlowcontrolApiserverV1beta2PriorityLevelConfigurationStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchInternalApiserverV1alpha1StorageVersionRequest(
	req PatchInternalApiserverV1alpha1StorageVersionReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchInternalApiserverV1alpha1StorageVersionStatusRequest(
	req PatchInternalApiserverV1alpha1StorageVersionStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchNetworkingV1IngressClassRequest(
	req PatchNetworkingV1IngressClassReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchNetworkingV1NamespacedIngressRequest(
	req PatchNetworkingV1NamespacedIngressReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchNetworkingV1NamespacedIngressStatusRequest(
	req PatchNetworkingV1NamespacedIngressStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchNetworkingV1NamespacedNetworkPolicyRequest(
	req PatchNetworkingV1NamespacedNetworkPolicyReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchNodeV1RuntimeClassRequest(
	req PatchNodeV1RuntimeClassReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchNodeV1alpha1RuntimeClassRequest(
	req PatchNodeV1alpha1RuntimeClassReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchNodeV1beta1RuntimeClassRequest(
	req PatchNodeV1beta1RuntimeClassReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchPolicyV1NamespacedPodDisruptionBudgetRequest(
	req PatchPolicyV1NamespacedPodDisruptionBudgetReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchPolicyV1NamespacedPodDisruptionBudgetStatusRequest(
	req PatchPolicyV1NamespacedPodDisruptionBudgetStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchPolicyV1beta1NamespacedPodDisruptionBudgetRequest(
	req PatchPolicyV1beta1NamespacedPodDisruptionBudgetReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchPolicyV1beta1NamespacedPodDisruptionBudgetStatusRequest(
	req PatchPolicyV1beta1NamespacedPodDisruptionBudgetStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchPolicyV1beta1PodSecurityPolicyRequest(
	req PatchPolicyV1beta1PodSecurityPolicyReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchRbacAuthorizationV1ClusterRoleRequest(
	req PatchRbacAuthorizationV1ClusterRoleReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchRbacAuthorizationV1ClusterRoleBindingRequest(
	req PatchRbacAuthorizationV1ClusterRoleBindingReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchRbacAuthorizationV1NamespacedRoleRequest(
	req PatchRbacAuthorizationV1NamespacedRoleReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchRbacAuthorizationV1NamespacedRoleBindingRequest(
	req PatchRbacAuthorizationV1NamespacedRoleBindingReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchSchedulingV1PriorityClassRequest(
	req PatchSchedulingV1PriorityClassReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchStorageV1CSIDriverRequest(
	req PatchStorageV1CSIDriverReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchStorageV1CSINodeRequest(
	req PatchStorageV1CSINodeReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchStorageV1StorageClassRequest(
	req PatchStorageV1StorageClassReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchStorageV1VolumeAttachmentRequest(
	req PatchStorageV1VolumeAttachmentReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchStorageV1VolumeAttachmentStatusRequest(
	req PatchStorageV1VolumeAttachmentStatusReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchStorageV1alpha1NamespacedCSIStorageCapacityRequest(
	req PatchStorageV1alpha1NamespacedCSIStorageCapacityReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}

func encodePatchStorageV1beta1NamespacedCSIStorageCapacityRequest(
	req PatchStorageV1beta1NamespacedCSIStorageCapacityReq,
	r *http.Request,
) error {
	_ = "STUB: not implemented"
	return nil
}
