// Code generated by ogen, DO NOT EDIT.

package api

func (s *IoK8sAPIAdmissionregistrationV1MutatingWebhook) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIAdmissionregistrationV1MutatingWebhookConfiguration) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIAdmissionregistrationV1MutatingWebhookConfigurationList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIAdmissionregistrationV1ValidatingWebhook) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIAdmissionregistrationV1ValidatingWebhookConfiguration) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIAdmissionregistrationV1ValidatingWebhookConfigurationList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIAdmissionregistrationV1WebhookClientConfig) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIApiserverinternalV1alpha1StorageVersionList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIAppsV1ControllerRevisionList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIAppsV1DaemonSet) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIAppsV1DaemonSetList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIAppsV1DaemonSetSpec) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIAppsV1Deployment) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIAppsV1DeploymentList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIAppsV1DeploymentSpec) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIAppsV1ReplicaSet) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIAppsV1ReplicaSetList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIAppsV1ReplicaSetSpec) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIAppsV1StatefulSet) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIAppsV1StatefulSetList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIAppsV1StatefulSetSpec) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIAutoscalingV1HorizontalPodAutoscalerList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIAutoscalingV2beta1HorizontalPodAutoscaler) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIAutoscalingV2beta1HorizontalPodAutoscalerList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIAutoscalingV2beta1HorizontalPodAutoscalerStatus) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIAutoscalingV2beta2HorizontalPodAutoscaler) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIAutoscalingV2beta2HorizontalPodAutoscalerList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIAutoscalingV2beta2HorizontalPodAutoscalerStatus) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIBatchV1CronJob) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIBatchV1CronJobList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIBatchV1CronJobSpec) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIBatchV1Job) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIBatchV1JobList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIBatchV1JobSpec) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIBatchV1JobTemplateSpec) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIBatchV1beta1CronJob) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIBatchV1beta1CronJobList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIBatchV1beta1CronJobSpec) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIBatchV1beta1JobTemplateSpec) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPICertificatesV1CertificateSigningRequest) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPICertificatesV1CertificateSigningRequestList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPICertificatesV1CertificateSigningRequestSpec) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s IoK8sAPICertificatesV1CertificateSigningRequestSpecExtra) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPICertificatesV1CertificateSigningRequestStatus) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPICoordinationV1LeaseList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1Affinity) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1CephFSPersistentVolumeSource) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPICoreV1CephFSVolumeSource) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1ComponentStatusList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1ConfigMap) Validate() error { _ = "STUB: not implemented"; return nil }

func (s IoK8sAPICoreV1ConfigMapBinaryData) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1ConfigMapList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1EndpointsList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1EventList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1LimitRange) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1LimitRangeList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1LimitRangeSpec) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1NamespaceList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1NodeAffinity) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1NodeList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1NodeSelector) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1PersistentVolume) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1PersistentVolumeClaimList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPICoreV1PersistentVolumeList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPICoreV1PersistentVolumeSpec) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPICoreV1Pod) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1PodList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1PodSpec) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1PodTemplate) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1PodTemplateList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1PodTemplateSpec) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1RBDPersistentVolumeSource) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPICoreV1RBDVolumeSource) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1ReplicationController) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPICoreV1ReplicationControllerList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPICoreV1ReplicationControllerSpec) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPICoreV1ResourceQuotaList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1Secret) Validate() error { _ = "STUB: not implemented"; return nil }

func (s IoK8sAPICoreV1SecretData) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1SecretList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1ServiceAccountList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1ServiceList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1TopologySelectorLabelRequirement) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPICoreV1TopologySelectorTerm) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPICoreV1Volume) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPICoreV1VolumeNodeAffinity) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIDiscoveryV1Endpoint) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIDiscoveryV1EndpointSlice) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIDiscoveryV1EndpointSliceList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIDiscoveryV1beta1Endpoint) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIDiscoveryV1beta1EndpointSlice) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIDiscoveryV1beta1EndpointSliceList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIEventsV1EventList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIEventsV1beta1EventList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIFlowcontrolV1beta1FlowSchema) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIFlowcontrolV1beta1FlowSchemaList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIFlowcontrolV1beta1FlowSchemaSpec) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIFlowcontrolV1beta1NonResourcePolicyRule) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIFlowcontrolV1beta1PolicyRulesWithSubjects) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIFlowcontrolV1beta1PriorityLevelConfigurationList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIFlowcontrolV1beta1ResourcePolicyRule) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIFlowcontrolV1beta2FlowSchema) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIFlowcontrolV1beta2FlowSchemaList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIFlowcontrolV1beta2FlowSchemaSpec) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIFlowcontrolV1beta2NonResourcePolicyRule) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIFlowcontrolV1beta2PolicyRulesWithSubjects) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIFlowcontrolV1beta2PriorityLevelConfigurationList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIFlowcontrolV1beta2ResourcePolicyRule) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPINetworkingV1HTTPIngressRuleValue) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPINetworkingV1Ingress) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPINetworkingV1IngressClassList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPINetworkingV1IngressList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPINetworkingV1IngressRule) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPINetworkingV1IngressSpec) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPINetworkingV1NetworkPolicyList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPINodeV1RuntimeClassList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPINodeV1alpha1RuntimeClassList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPINodeV1beta1RuntimeClassList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIPolicyV1PodDisruptionBudgetList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIPolicyV1beta1PodDisruptionBudgetList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIPolicyV1beta1PodSecurityPolicy) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIPolicyV1beta1PodSecurityPolicyList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIPolicyV1beta1PodSecurityPolicySpec) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIPolicyV1beta1RuntimeClassStrategyOptions) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIRbacV1ClusterRole) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIRbacV1ClusterRoleBindingList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIRbacV1ClusterRoleList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIRbacV1PolicyRule) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIRbacV1Role) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIRbacV1RoleBindingList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIRbacV1RoleList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPISchedulingV1PriorityClassList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIStorageV1CSIDriverList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIStorageV1CSINode) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIStorageV1CSINodeList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIStorageV1CSINodeSpec) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIStorageV1StorageClass) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIStorageV1StorageClassList) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIStorageV1VolumeAttachment) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *IoK8sAPIStorageV1VolumeAttachmentList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIStorageV1VolumeAttachmentSource) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIStorageV1VolumeAttachmentSpec) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIStorageV1alpha1CSIStorageCapacityList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sAPIStorageV1beta1CSIStorageCapacityList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceConversion) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinition) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionSpec) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionVersion) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

// optional

func (s *IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceValidation) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

// optional

func (s *IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSONSchemaProps) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

// optional

func (s IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSONSchemaPropsDefinitions) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSONSchemaPropsPatternProperties) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSONSchemaPropsProperties) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sApiextensionsApiserverPkgApisApiextensionsV1WebhookClientConfig) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sApiextensionsApiserverPkgApisApiextensionsV1WebhookConversion) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sApimachineryPkgApisMetaV1APIGroup) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sApimachineryPkgApisMetaV1APIGroupList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sApimachineryPkgApisMetaV1APIResource) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sApimachineryPkgApisMetaV1APIResourceList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sApimachineryPkgApisMetaV1APIVersions) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sKubeAggregatorPkgApisApiregistrationV1APIService) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceList) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceSpec) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchAdmissionregistrationV1MutatingWebhookConfigurationCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchAdmissionregistrationV1MutatingWebhookConfigurationOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchAdmissionregistrationV1ValidatingWebhookConfigurationCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchAdmissionregistrationV1ValidatingWebhookConfigurationOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchApiextensionsV1CustomResourceDefinitionCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchApiextensionsV1CustomResourceDefinitionOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchApiextensionsV1CustomResourceDefinitionStatusCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchApiextensionsV1CustomResourceDefinitionStatusOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchApiregistrationV1APIServiceCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchApiregistrationV1APIServiceOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchApiregistrationV1APIServiceStatusCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchApiregistrationV1APIServiceStatusOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchAppsV1NamespacedDaemonSetCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchAppsV1NamespacedDaemonSetOK) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PatchAppsV1NamespacedDaemonSetStatusCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchAppsV1NamespacedDaemonSetStatusOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchAppsV1NamespacedDeploymentCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchAppsV1NamespacedDeploymentOK) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PatchAppsV1NamespacedDeploymentStatusCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchAppsV1NamespacedDeploymentStatusOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchAppsV1NamespacedReplicaSetCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchAppsV1NamespacedReplicaSetOK) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PatchAppsV1NamespacedReplicaSetStatusCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchAppsV1NamespacedReplicaSetStatusOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchAppsV1NamespacedStatefulSetCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchAppsV1NamespacedStatefulSetOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchAppsV1NamespacedStatefulSetStatusCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchAppsV1NamespacedStatefulSetStatusOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerStatusCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerStatusOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchAutoscalingV2beta2NamespacedHorizontalPodAutoscalerCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchAutoscalingV2beta2NamespacedHorizontalPodAutoscalerOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchAutoscalingV2beta2NamespacedHorizontalPodAutoscalerStatusCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchAutoscalingV2beta2NamespacedHorizontalPodAutoscalerStatusOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchBatchV1NamespacedCronJobCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchBatchV1NamespacedCronJobOK) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PatchBatchV1NamespacedCronJobStatusCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchBatchV1NamespacedCronJobStatusOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchBatchV1NamespacedJobCreated) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PatchBatchV1NamespacedJobOK) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PatchBatchV1NamespacedJobStatusCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchBatchV1NamespacedJobStatusOK) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PatchBatchV1beta1NamespacedCronJobCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchBatchV1beta1NamespacedCronJobOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchBatchV1beta1NamespacedCronJobStatusCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchBatchV1beta1NamespacedCronJobStatusOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchCertificatesV1CertificateSigningRequestApprovalCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchCertificatesV1CertificateSigningRequestApprovalOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchCertificatesV1CertificateSigningRequestCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchCertificatesV1CertificateSigningRequestOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchCertificatesV1CertificateSigningRequestStatusCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchCertificatesV1CertificateSigningRequestStatusOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchCoreV1NamespacedConfigMapCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchCoreV1NamespacedConfigMapOK) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PatchCoreV1NamespacedLimitRangeCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchCoreV1NamespacedLimitRangeOK) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PatchCoreV1NamespacedPodCreated) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PatchCoreV1NamespacedPodEphemeralcontainersCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchCoreV1NamespacedPodEphemeralcontainersOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchCoreV1NamespacedPodOK) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PatchCoreV1NamespacedPodStatusCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchCoreV1NamespacedPodStatusOK) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PatchCoreV1NamespacedPodTemplateCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchCoreV1NamespacedPodTemplateOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchCoreV1NamespacedReplicationControllerCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchCoreV1NamespacedReplicationControllerOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchCoreV1NamespacedReplicationControllerStatusCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchCoreV1NamespacedReplicationControllerStatusOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchCoreV1NamespacedSecretCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchCoreV1NamespacedSecretOK) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PatchCoreV1PersistentVolumeCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchCoreV1PersistentVolumeOK) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PatchCoreV1PersistentVolumeStatusCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchCoreV1PersistentVolumeStatusOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchDiscoveryV1NamespacedEndpointSliceCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchDiscoveryV1NamespacedEndpointSliceOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchDiscoveryV1beta1NamespacedEndpointSliceCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchDiscoveryV1beta1NamespacedEndpointSliceOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchFlowcontrolApiserverV1beta1FlowSchemaCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchFlowcontrolApiserverV1beta1FlowSchemaOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchFlowcontrolApiserverV1beta1FlowSchemaStatusCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchFlowcontrolApiserverV1beta1FlowSchemaStatusOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchFlowcontrolApiserverV1beta2FlowSchemaCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchFlowcontrolApiserverV1beta2FlowSchemaOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchFlowcontrolApiserverV1beta2FlowSchemaStatusCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchFlowcontrolApiserverV1beta2FlowSchemaStatusOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchNetworkingV1NamespacedIngressCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchNetworkingV1NamespacedIngressOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchNetworkingV1NamespacedIngressStatusCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchNetworkingV1NamespacedIngressStatusOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchPolicyV1beta1PodSecurityPolicyCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchPolicyV1beta1PodSecurityPolicyOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchRbacAuthorizationV1ClusterRoleCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchRbacAuthorizationV1ClusterRoleOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchRbacAuthorizationV1NamespacedRoleCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchRbacAuthorizationV1NamespacedRoleOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchStorageV1CSINodeCreated) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PatchStorageV1CSINodeOK) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PatchStorageV1StorageClassCreated) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PatchStorageV1StorageClassOK) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PatchStorageV1VolumeAttachmentCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchStorageV1VolumeAttachmentOK) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PatchStorageV1VolumeAttachmentStatusCreated) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

func (s *PatchStorageV1VolumeAttachmentStatusOK) Validate() error {
	_ = "STUB: not implemented"
	return nil
}
