// Code generated by ogen, DO NOT EDIT.

package techempower

// SetFake set fake values.
func (s *HelloWorld) SetFake() { _ = "STUB: not implemented"; return }

// SetFake set fake values.
func (s *WorldObject) SetFake() { _ = "STUB: not implemented"; return }

// SetFake set fake values.
func (s *WorldObjects) SetFake() { _ = "STUB: not implemented"; return }
