// Code generated by ogen, DO NOT EDIT.

package api

func (s *Board) Validate() error { _ = "STUB: not implemented"; return nil }

func (s Boards) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *Captcha) Validate() error { _ = "STUB: not implemented"; return nil }

func (s CaptchaType) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *Error) Validate() error { _ = "STUB: not implemented"; return nil }

func (s ErrorCode) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *File) Validate() error { _ = "STUB: not implemented"; return nil }

func (s FileType) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *Like) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *MobilePost) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *MobileThreadLastInfo) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *MobileThreadPostsAfter) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *Passcode) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *Post) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PostingNewPost) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *PostingNewThread) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *Report) Validate() error { _ = "STUB: not implemented"; return nil }

func (s UserPostingPostOK) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *UserPostingPostReq) Validate() error { _ = "STUB: not implemented"; return nil }
