// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleBasicAuth handles basicAuth security.
	HandleBasicAuth(ctx context.Context, operationName OperationName, t BasicAuth) (context.Context, error)
	// HandleBearerToken handles bearerToken security.
	HandleBearerToken(ctx context.Context, operationName OperationName, t BearerToken) (context.Context, error)
	// HandleCookieKey handles cookieKey security.
	HandleCookieKey(ctx context.Context, operationName OperationName, t CookieKey) (context.Context, error)
	// HandleCustom handles custom security.
	HandleCustom(ctx context.Context, operationName OperationName, t Custom) (context.Context, error)
	// HandleHeaderKey handles headerKey security.
	HandleHeaderKey(ctx context.Context, operationName OperationName, t HeaderKey) (context.Context, error)
	// HandleQueryKey handles queryKey security.
	HandleQueryKey(ctx context.Context, operationName OperationName, t QueryKey) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	_ = "STUB: not implemented"
	return "", false
}

// operationRolesBasicAuth is a private map storing roles per operation.
var operationRolesBasicAuth = map[string][]string{
	DisjointSecurityOperation:  []string{},
	IntersectSecurityOperation: []string{},
}

// GetRolesForBasicAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForBasicAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForBasicAuth(operation string) []string { _ = "STUB: not implemented"; return nil }

// Return a copy to prevent external modification

// operationRolesBearerToken is a private map storing roles per operation.
var operationRolesBearerToken = map[string][]string{
	IntersectSecurityOperation: []string{},
}

// GetRolesForBearerToken returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForBearerToken(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForBearerToken(operation string) []string { _ = "STUB: not implemented"; return nil }

// Return a copy to prevent external modification

// operationRolesCookieKey is a private map storing roles per operation.
var operationRolesCookieKey = map[string][]string{
	DisjointSecurityOperation: []string{},
}

// GetRolesForCookieKey returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForCookieKey(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForCookieKey(operation string) []string { _ = "STUB: not implemented"; return nil }

// Return a copy to prevent external modification

// operationRolesCustom is a private map storing roles per operation.
var operationRolesCustom = map[string][]string{
	CustomSecurityOperation: []string{},
}

// GetRolesForCustom returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForCustom(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForCustom(operation string) []string { _ = "STUB: not implemented"; return nil }

// Return a copy to prevent external modification

// operationRolesHeaderKey is a private map storing roles per operation.
var operationRolesHeaderKey = map[string][]string{
	DisjointSecurityOperation:  []string{},
	IntersectSecurityOperation: []string{},
}

// GetRolesForHeaderKey returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForHeaderKey(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForHeaderKey(operation string) []string { _ = "STUB: not implemented"; return nil }

// Return a copy to prevent external modification

// operationRolesQueryKey is a private map storing roles per operation.
var operationRolesQueryKey = map[string][]string{
	DisjointSecurityOperation: []string{},
	OptionalSecurityOperation: []string{
		"admin",
	},
}

// GetRolesForQueryKey returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForQueryKey(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForQueryKey(operation string) []string { _ = "STUB: not implemented"; return nil }

// Return a copy to prevent external modification

func (s *Server) securityBasicAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	_ = "STUB: not implemented"
	return *new(context.Context), false, nil
}

func (s *Server) securityBearerToken(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	_ = "STUB: not implemented"
	return *new(context.Context), false, nil
}

func (s *Server) securityCookieKey(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	_ = "STUB: not implemented"
	return *new(context.Context), false, nil
}

// if NO error

func (s *Server) securityCustom(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	_ = "STUB: not implemented"
	return *new(context.Context), false, nil
}

func (s *Server) securityHeaderKey(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	_ = "STUB: not implemented"
	return *new(context.Context), false, nil
}

func (s *Server) securityQueryKey(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	_ = "STUB: not implemented"
	return *new(context.Context), false, nil
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// BasicAuth provides basicAuth security value.
	BasicAuth(ctx context.Context, operationName OperationName, client *Client) (BasicAuth, error)
	// BearerToken provides bearerToken security value.
	BearerToken(ctx context.Context, operationName OperationName, client *Client) (BearerToken, error)
	// CookieKey provides cookieKey security value.
	CookieKey(ctx context.Context, operationName OperationName, client *Client) (CookieKey, error)
	// Custom provides custom security value.
	Custom(ctx context.Context, operationName OperationName, req *http.Request, client *Client) error
	// HeaderKey provides headerKey security value.
	HeaderKey(ctx context.Context, operationName OperationName, client *Client) (HeaderKey, error)
	// QueryKey provides queryKey security value.
	QueryKey(ctx context.Context, operationName OperationName, client *Client) (QueryKey, error)
}

func (s *Client) securityBasicAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	_ = "STUB: not implemented"
	return nil
}

func (s *Client) securityBearerToken(ctx context.Context, operationName OperationName, req *http.Request) error {
	_ = "STUB: not implemented"
	return nil
}

func (s *Client) securityCookieKey(ctx context.Context, operationName OperationName, req *http.Request) error {
	_ = "STUB: not implemented"
	return nil
}

func (s *Client) securityCustom(ctx context.Context, operationName OperationName, req *http.Request) error {
	_ = "STUB: not implemented"
	return nil
}

func (s *Client) securityHeaderKey(ctx context.Context, operationName OperationName, req *http.Request) error {
	_ = "STUB: not implemented"
	return nil
}

func (s *Client) securityQueryKey(ctx context.Context, operationName OperationName, req *http.Request) error {
	_ = "STUB: not implemented"
	return nil
}
