// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/url"
)

func trimTrailingSlashes(u *url.URL) { _ = "STUB: not implemented"; return }

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	TestInvoker
	// GetMixedData invokes getMixedData operation.
	//
	// GET /mixed-data
	GetMixedData(ctx context.Context) (GetMixedDataRes, error)
	// GetNormalData invokes getNormalData operation.
	//
	// GET /normal-data
	GetNormalData(ctx context.Context) (*GetNormalDataOK, error)
	// GetRawData invokes getRawData operation.
	//
	// GET /raw-data
	GetRawData(ctx context.Context) (GetRawDataRes, error)
}

// TestInvoker invokes operations described by OpenAPI v3 specification.
//
// x-gen-operation-group: Test
type TestInvoker interface {
	// GetRawDataInsideOperationGroup invokes getRawDataInsideOperationGroup operation.
	//
	// GET /raw-data-inside-operation-group
	GetRawDataInsideOperationGroup(ctx context.Context) (GetRawDataInsideOperationGroupRes, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	baseClient
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, opts ...ClientOption) (*Client, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

func (c *Client) requestURL(ctx context.Context) *url.URL { _ = "STUB: not implemented"; return nil }

// GetMixedData invokes getMixedData operation.
//
// GET /mixed-data
func (c *Client) GetMixedData(ctx context.Context) (GetMixedDataRes, error) {
	_ = "STUB: not implemented"
	return *new(GetMixedDataRes), nil
}

func (c *Client) sendGetMixedData(ctx context.Context) (res GetMixedDataRes, err error) {
	_ = "STUB: not implemented"
	return *new(GetMixedDataRes), nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// GetNormalData invokes getNormalData operation.
//
// GET /normal-data
func (c *Client) GetNormalData(ctx context.Context) (*GetNormalDataOK, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) sendGetNormalData(ctx context.Context) (res *GetNormalDataOK, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// GetRawData invokes getRawData operation.
//
// GET /raw-data
func (c *Client) GetRawData(ctx context.Context) (GetRawDataRes, error) {
	_ = "STUB: not implemented"
	return *new(GetRawDataRes), nil
}

func (c *Client) sendGetRawData(ctx context.Context) (res GetRawDataRes, err error) {
	_ = "STUB: not implemented"
	return *new(GetRawDataRes), nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// GetRawDataInsideOperationGroup invokes getRawDataInsideOperationGroup operation.
//
// GET /raw-data-inside-operation-group
func (c *Client) GetRawDataInsideOperationGroup(ctx context.Context) (GetRawDataInsideOperationGroupRes, error) {
	_ = "STUB: not implemented"
	return *new(GetRawDataInsideOperationGroupRes), nil
}

func (c *Client) sendGetRawDataInsideOperationGroup(ctx context.Context) (res GetRawDataInsideOperationGroupRes, err error) {
	_ = "STUB: not implemented"
	return *new(GetRawDataInsideOperationGroupRes), nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.
