// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
)

func decodeCreateItemsResponse(resp *http.Response) (res *CreateItemsOK, _ error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Code 200.
