// Code generated by ogen, DO NOT EDIT.

package api

import (
	"io"
)

type AllRequestBodiesApplicationJSON SimpleObject

func (*AllRequestBodiesApplicationJSON) allRequestBodiesReq() { _ = "STUB: not implemented"; return }

type AllRequestBodiesApplicationXWwwFormUrlencoded SimpleObject

func (*AllRequestBodiesApplicationXWwwFormUrlencoded) allRequestBodiesReq() {
	_ = "STUB: not implemented"
	return
}

type AllRequestBodiesOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s AllRequestBodiesOK) Read(p []byte) (n int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

type AllRequestBodiesOptionalApplicationJSON SimpleObject

func (*AllRequestBodiesOptionalApplicationJSON) allRequestBodiesOptionalReq() {
	_ = "STUB: not implemented"
	return
}

type AllRequestBodiesOptionalApplicationXWwwFormUrlencoded SimpleObject

func (*AllRequestBodiesOptionalApplicationXWwwFormUrlencoded) allRequestBodiesOptionalReq() {
	_ = "STUB: not implemented"
	return
}

type AllRequestBodiesOptionalOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s AllRequestBodiesOptionalOK) Read(p []byte) (n int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

type AllRequestBodiesOptionalReqApplicationOctetStream struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s AllRequestBodiesOptionalReqApplicationOctetStream) Read(p []byte) (n int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (*AllRequestBodiesOptionalReqApplicationOctetStream) allRequestBodiesOptionalReq() {
	_ = "STUB: not implemented"
	return
}

type AllRequestBodiesOptionalReqEmptyBody struct{}

func (*AllRequestBodiesOptionalReqEmptyBody) allRequestBodiesOptionalReq() {
	_ = "STUB: not implemented"
	return
}

type AllRequestBodiesOptionalReqTextPlain struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s AllRequestBodiesOptionalReqTextPlain) Read(p []byte) (n int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (*AllRequestBodiesOptionalReqTextPlain) allRequestBodiesOptionalReq() {
	_ = "STUB: not implemented"
	return
}

type AllRequestBodiesReqApplicationOctetStream struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s AllRequestBodiesReqApplicationOctetStream) Read(p []byte) (n int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (*AllRequestBodiesReqApplicationOctetStream) allRequestBodiesReq() {
	_ = "STUB: not implemented"
	return
}

type AllRequestBodiesReqTextPlain struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s AllRequestBodiesReqTextPlain) Read(p []byte) (n int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (*AllRequestBodiesReqTextPlain) allRequestBodiesReq() { _ = "STUB: not implemented"; return }

type Base64RequestOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s Base64RequestOK) Read(p []byte) (n int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

type Base64RequestReq struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s Base64RequestReq) Read(p []byte) (n int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

type MaskContentTypeOptionalReq struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s MaskContentTypeOptionalReq) Read(p []byte) (n int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// MaskContentTypeOptionalReqWithContentType wraps MaskContentTypeOptionalReq with Content-Type.
type MaskContentTypeOptionalReqWithContentType struct {
	ContentType string
	Content     MaskContentTypeOptionalReq
}

// GetContentType returns the value of ContentType.
func (s *MaskContentTypeOptionalReqWithContentType) GetContentType() string {
	_ = "STUB: not implemented"
	return ""

	// GetContent returns the value of Content.
}

func (s *MaskContentTypeOptionalReqWithContentType) GetContent() MaskContentTypeOptionalReq {
	_ = "STUB: not implemented"

	// SetContentType sets the value of ContentType.
	return *new(MaskContentTypeOptionalReq)
}

func (s *MaskContentTypeOptionalReqWithContentType) SetContentType(val string) {
	_ = "STUB: not implemented"
	return

	// SetContent sets the value of Content.
}

func (s *MaskContentTypeOptionalReqWithContentType) SetContent(val MaskContentTypeOptionalReq) {
	_ = "STUB: not implemented"
	return
}

type MaskContentTypeReq struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s MaskContentTypeReq) Read(p []byte) (n int, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// MaskContentTypeReqWithContentType wraps MaskContentTypeReq with Content-Type.
type MaskContentTypeReqWithContentType struct {
	ContentType string
	Content     MaskContentTypeReq
}

// GetContentType returns the value of ContentType.
func (s *MaskContentTypeReqWithContentType) GetContentType() string {
	_ = "STUB: not implemented"
	return ""

	// GetContent returns the value of Content.
}

func (s *MaskContentTypeReqWithContentType) GetContent() MaskContentTypeReq {
	_ = "STUB: not implemented"

	// SetContentType sets the value of ContentType.
	return *new(MaskContentTypeReq)
}

func (s *MaskContentTypeReqWithContentType) SetContentType(val string) {
	_ = "STUB: not implemented"
	return

	// SetContent sets the value of Content.
}

func (s *MaskContentTypeReqWithContentType) SetContent(val MaskContentTypeReq) {
	_ = "STUB: not implemented"

	// Ref: #/components/schemas/MaskResponse
	return
}

type MaskResponse struct {
	ContentType string `json:"contentType"`
	Content     string `json:"content"`
}

// GetContentType returns the value of ContentType.
func (s *MaskResponse) GetContentType() string { _ = "STUB: not implemented"; return "" }

// GetContent returns the value of Content.
func (s *MaskResponse) GetContent() string {
	_ = "STUB: not implemented"

	// SetContentType sets the value of ContentType.
	return ""
}

func (s *MaskResponse) SetContentType(val string) { _ = "STUB: not implemented"; return }

// SetContent sets the value of Content.
func (s *MaskResponse) SetContent(val string) {
	_ = "STUB: not implemented"

	// NewOptInt returns new OptInt with value set to v.
	return
}

func NewOptInt(v int) OptInt { _ = "STUB: not implemented"; return *new(OptInt) }

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool {
	_ = "STUB: not implemented"

	// Reset unsets value.
	return false
}

func (o *OptInt) Reset() { _ = "STUB: not implemented"; return }

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) { _ = "STUB: not implemented"; return }

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) { _ = "STUB: not implemented"; return 0, false }

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int { _ = "STUB: not implemented"; return 0 }

// Ref: #/components/schemas/SimpleObject
type SimpleObject struct {
	Name string `json:"name"`
	Age  OptInt `json:"age"`
}

// GetName returns the value of Name.
func (s *SimpleObject) GetName() string {
	_ = "STUB: not implemented"

	// GetAge returns the value of Age.
	return ""
}

func (s *SimpleObject) GetAge() OptInt {
	_ = "STUB: not implemented"

	// SetName sets the value of Name.
	return *new(OptInt)
}

func (s *SimpleObject) SetName(val string) {
	_ = "STUB: not implemented"

	// SetAge sets the value of Age.
	return
}

func (s *SimpleObject) SetAge(val OptInt) {
	_ = "STUB: not implemented"

	// Ref: #/components/schemas/SimpleObject
	return
}

type SimpleObjectMultipart struct {
	Name string `json:"name"`
	Age  OptInt `json:"age"`
}

// GetName returns the value of Name.
func (s *SimpleObjectMultipart) GetName() string {
	_ = "STUB: not implemented"

	// GetAge returns the value of Age.
	return ""
}

func (s *SimpleObjectMultipart) GetAge() OptInt {
	_ = "STUB: not implemented"

	// SetName sets the value of Name.
	return *new(OptInt)
}

func (s *SimpleObjectMultipart) SetName(val string) {
	_ = "STUB: not implemented"

	// SetAge sets the value of Age.
	return
}

func (s *SimpleObjectMultipart) SetAge(val OptInt) { _ = "STUB: not implemented"; return }

func (*SimpleObjectMultipart) allRequestBodiesOptionalReq() { _ = "STUB: not implemented"; return }
func (*SimpleObjectMultipart) allRequestBodiesReq()         { _ = "STUB: not implemented"; return }
