// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	"go.opentelemetry.io/otel/trace"
)

func encodeCreateIntegrationItemsResponse(response *CreateIntegrationItemsOK, w http.ResponseWriter, span trace.Span) error {
	_ = "STUB: not implemented"
	return nil
}
