// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"
)

type CreatePetCategoriesReq struct {
	Name string `json:"name"`
	Pets []int  `json:"pets"`
}

// GetName returns the value of Name.
func (s *CreatePetCategoriesReq) GetName() string {
	_ = "STUB: not implemented"

	// GetPets returns the value of Pets.
	return ""
}

func (s *CreatePetCategoriesReq) GetPets() []int {
	_ = "STUB: not implemented"

	// SetName sets the value of Name.
	return nil
}

func (s *CreatePetCategoriesReq) SetName(val string) {
	_ = "STUB: not implemented"

	// SetPets sets the value of Pets.
	return
}

func (s *CreatePetCategoriesReq) SetPets(val []int) { _ = "STUB: not implemented"; return }

type CreatePetFriendsReq struct {
	Name       string      `json:"name"`
	Weight     OptInt      `json:"weight"`
	Birthday   OptDateTime `json:"birthday"`
	Categories []int       `json:"categories"`
	Owner      int         `json:"owner"`
	Friends    []int       `json:"friends"`
}

// GetName returns the value of Name.
func (s *CreatePetFriendsReq) GetName() string {
	_ = "STUB: not implemented"

	// GetWeight returns the value of Weight.
	return ""
}

func (s *CreatePetFriendsReq) GetWeight() OptInt {
	_ = "STUB: not implemented"

	// GetBirthday returns the value of Birthday.
	return *new(OptInt)
}

func (s *CreatePetFriendsReq) GetBirthday() OptDateTime {
	_ = "STUB: not implemented"

	// GetCategories returns the value of Categories.
	return *new(OptDateTime)
}

func (s *CreatePetFriendsReq) GetCategories() []int { _ = "STUB: not implemented"; return nil }

// GetOwner returns the value of Owner.
func (s *CreatePetFriendsReq) GetOwner() int {
	_ = "STUB: not implemented"

	// GetFriends returns the value of Friends.
	return 0
}

func (s *CreatePetFriendsReq) GetFriends() []int {
	_ = "STUB: not implemented"

	// SetName sets the value of Name.
	return nil
}

func (s *CreatePetFriendsReq) SetName(val string) {
	_ = "STUB: not implemented"

	// SetWeight sets the value of Weight.
	return
}

func (s *CreatePetFriendsReq) SetWeight(val OptInt) {
	_ = "STUB: not implemented"

	// SetBirthday sets the value of Birthday.
	return
}

func (s *CreatePetFriendsReq) SetBirthday(val OptDateTime) {
	_ = "STUB: not implemented"

	// SetCategories sets the value of Categories.
	return
}

func (s *CreatePetFriendsReq) SetCategories(val []int) {
	_ = "STUB: not implemented"

	// SetOwner sets the value of Owner.
	return
}

func (s *CreatePetFriendsReq) SetOwner(val int) {
	_ = "STUB: not implemented"

	// SetFriends sets the value of Friends.
	return
}

func (s *CreatePetFriendsReq) SetFriends(val []int) { _ = "STUB: not implemented"; return }

type CreatePetOwnerReq struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
	Pets []int  `json:"pets"`
}

// GetName returns the value of Name.
func (s *CreatePetOwnerReq) GetName() string {
	_ = "STUB: not implemented"

	// GetAge returns the value of Age.
	return ""
}

func (s *CreatePetOwnerReq) GetAge() int {
	_ = "STUB: not implemented"

	// GetPets returns the value of Pets.
	return 0
}

func (s *CreatePetOwnerReq) GetPets() []int {
	_ = "STUB: not implemented"

	// SetName sets the value of Name.
	return nil
}

func (s *CreatePetOwnerReq) SetName(val string) {
	_ = "STUB: not implemented"

	// SetAge sets the value of Age.
	return
}

func (s *CreatePetOwnerReq) SetAge(val int) {
	_ = "STUB: not implemented"

	// SetPets sets the value of Pets.
	return
}

func (s *CreatePetOwnerReq) SetPets(val []int) { _ = "STUB: not implemented"; return }

type CreatePetReq struct {
	Name       string      `json:"name"`
	Weight     OptInt      `json:"weight"`
	Birthday   OptDateTime `json:"birthday"`
	Categories []int       `json:"categories"`
	Owner      int         `json:"owner"`
	Friends    []int       `json:"friends"`
}

// GetName returns the value of Name.
func (s *CreatePetReq) GetName() string {
	_ = "STUB: not implemented"

	// GetWeight returns the value of Weight.
	return ""
}

func (s *CreatePetReq) GetWeight() OptInt {
	_ = "STUB: not implemented"

	// GetBirthday returns the value of Birthday.
	return *new(OptInt)
}

func (s *CreatePetReq) GetBirthday() OptDateTime {
	_ = "STUB: not implemented"

	// GetCategories returns the value of Categories.
	return *new(OptDateTime)
}

func (s *CreatePetReq) GetCategories() []int { _ = "STUB: not implemented"; return nil }

// GetOwner returns the value of Owner.
func (s *CreatePetReq) GetOwner() int {
	_ = "STUB: not implemented"

	// GetFriends returns the value of Friends.
	return 0
}

func (s *CreatePetReq) GetFriends() []int {
	_ = "STUB: not implemented"

	// SetName sets the value of Name.
	return nil
}

func (s *CreatePetReq) SetName(val string) {
	_ = "STUB: not implemented"

	// SetWeight sets the value of Weight.
	return
}

func (s *CreatePetReq) SetWeight(val OptInt) {
	_ = "STUB: not implemented"

	// SetBirthday sets the value of Birthday.
	return
}

func (s *CreatePetReq) SetBirthday(val OptDateTime) {
	_ = "STUB: not implemented"

	// SetCategories sets the value of Categories.
	return
}

func (s *CreatePetReq) SetCategories(val []int) {
	_ = "STUB: not implemented"

	// SetOwner sets the value of Owner.
	return
}

func (s *CreatePetReq) SetOwner(val int) {
	_ = "STUB: not implemented"

	// SetFriends sets the value of Friends.
	return
}

func (s *CreatePetReq) SetFriends(val []int) {
	_ = "STUB: not implemented"

	// DeletePetNoContent is response for DeletePet operation.
	return
}

type DeletePetNoContent struct{}

func (*DeletePetNoContent) deletePetRes() {
	_ = "STUB: not implemented"

	// DeletePetOwnerNoContent is response for DeletePetOwner operation.
	return
}

type DeletePetOwnerNoContent struct{}

func (*DeletePetOwnerNoContent) deletePetOwnerRes() { _ = "STUB: not implemented"; return }

type ListPetCategoriesOKApplicationJSON []PetCategoriesList

func (*ListPetCategoriesOKApplicationJSON) listPetCategoriesRes() {
	_ = "STUB: not implemented"
	return
}

type ListPetFriendsOKApplicationJSON []PetFriendsList

func (*ListPetFriendsOKApplicationJSON) listPetFriendsRes() { _ = "STUB: not implemented"; return }

type ListPetOKApplicationJSON []PetList

func (*ListPetOKApplicationJSON) listPetRes() {
	_ = "STUB: not implemented"

	// NewOptDateTime returns new OptDateTime with value set to v.
	return
}

func NewOptDateTime(v time.Time) OptDateTime { _ = "STUB: not implemented"; return *new(OptDateTime) }

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool {
	_ = "STUB: not implemented"

	// Reset unsets value.
	return false
}

func (o *OptDateTime) Reset() { _ = "STUB: not implemented"; return }

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) { _ = "STUB: not implemented"; return }

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	_ = "STUB: not implemented"
	return *new(time.Time), false
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time { _ = "STUB: not implemented"; return *new(time.Time) }

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt { _ = "STUB: not implemented"; return *new(OptInt) }

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool {
	_ = "STUB: not implemented"

	// Reset unsets value.
	return false
}

func (o *OptInt) Reset() { _ = "STUB: not implemented"; return }

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) { _ = "STUB: not implemented"; return }

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) { _ = "STUB: not implemented"; return 0, false }

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int { _ = "STUB: not implemented"; return 0 }

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 { _ = "STUB: not implemented"; return *new(OptInt32) }

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool {
	_ = "STUB: not implemented"

	// Reset unsets value.
	return false
}

func (o *OptInt32) Reset() { _ = "STUB: not implemented"; return }

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) { _ = "STUB: not implemented"; return }

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) { _ = "STUB: not implemented"; return 0, false }

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 { _ = "STUB: not implemented"; return 0 }

// Ref: #/components/schemas/Pet_CategoriesCreate
type PetCategoriesCreate struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

// GetID returns the value of ID.
func (s *PetCategoriesCreate) GetID() int {
	_ = "STUB: not implemented"

	// GetName returns the value of Name.
	return 0
}

func (s *PetCategoriesCreate) GetName() string {
	_ = "STUB: not implemented"

	// SetID sets the value of ID.
	return ""
}

func (s *PetCategoriesCreate) SetID(val int) {
	_ = "STUB: not implemented"

	// SetName sets the value of Name.
	return
}

func (s *PetCategoriesCreate) SetName(val string) { _ = "STUB: not implemented"; return }

func (*PetCategoriesCreate) createPetCategoriesRes() {
	_ = "STUB: not implemented"

	// Ref: #/components/schemas/Pet_CategoriesList
	return
}

type PetCategoriesList struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

// GetID returns the value of ID.
func (s *PetCategoriesList) GetID() int {
	_ = "STUB: not implemented"

	// GetName returns the value of Name.
	return 0
}

func (s *PetCategoriesList) GetName() string {
	_ = "STUB: not implemented"

	// SetID sets the value of ID.
	return ""
}

func (s *PetCategoriesList) SetID(val int) {
	_ = "STUB: not implemented"

	// SetName sets the value of Name.
	return
}

func (s *PetCategoriesList) SetName(val string) {
	_ = "STUB: not implemented"

	// Ref: #/components/schemas/PetCreate
	return
}

type PetCreate struct {
	ID         int                   `json:"id"`
	Name       string                `json:"name"`
	Weight     OptInt                `json:"weight"`
	Birthday   OptDateTime           `json:"birthday"`
	Categories []PetCreateCategories `json:"categories"`
	Owner      PetCreateOwner        `json:"owner"`
}

// GetID returns the value of ID.
func (s *PetCreate) GetID() int {
	_ = "STUB: not implemented"

	// GetName returns the value of Name.
	return 0
}

func (s *PetCreate) GetName() string {
	_ = "STUB: not implemented"

	// GetWeight returns the value of Weight.
	return ""
}

func (s *PetCreate) GetWeight() OptInt {
	_ = "STUB: not implemented"

	// GetBirthday returns the value of Birthday.
	return *new(OptInt)
}

func (s *PetCreate) GetBirthday() OptDateTime {
	_ = "STUB: not implemented"

	// GetCategories returns the value of Categories.
	return *new(OptDateTime)
}

func (s *PetCreate) GetCategories() []PetCreateCategories { _ = "STUB: not implemented"; return nil }

// GetOwner returns the value of Owner.
func (s *PetCreate) GetOwner() PetCreateOwner {
	_ = "STUB: not implemented"

	// SetID sets the value of ID.
	return *new(PetCreateOwner)
}

func (s *PetCreate) SetID(val int) {
	_ = "STUB: not implemented"

	// SetName sets the value of Name.
	return
}

func (s *PetCreate) SetName(val string) {
	_ = "STUB: not implemented"

	// SetWeight sets the value of Weight.
	return
}

func (s *PetCreate) SetWeight(val OptInt) {
	_ = "STUB: not implemented"

	// SetBirthday sets the value of Birthday.
	return
}

func (s *PetCreate) SetBirthday(val OptDateTime) {
	_ = "STUB: not implemented"

	// SetCategories sets the value of Categories.
	return
}

func (s *PetCreate) SetCategories(val []PetCreateCategories) {
	_ = "STUB: not implemented"

	// SetOwner sets the value of Owner.
	return
}

func (s *PetCreate) SetOwner(val PetCreateOwner) { _ = "STUB: not implemented"; return }

func (*PetCreate) createPetRes() {
	_ = "STUB: not implemented"

	// Ref: #/components/schemas/PetCreate_Categories
	return
}

type PetCreateCategories struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

// GetID returns the value of ID.
func (s *PetCreateCategories) GetID() int {
	_ = "STUB: not implemented"

	// GetName returns the value of Name.
	return 0
}

func (s *PetCreateCategories) GetName() string {
	_ = "STUB: not implemented"

	// SetID sets the value of ID.
	return ""
}

func (s *PetCreateCategories) SetID(val int) {
	_ = "STUB: not implemented"

	// SetName sets the value of Name.
	return
}

func (s *PetCreateCategories) SetName(val string) {
	_ = "STUB: not implemented"

	// Ref: #/components/schemas/PetCreate_Owner
	return
}

type PetCreateOwner struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
	Age  int    `json:"age"`
}

// GetID returns the value of ID.
func (s *PetCreateOwner) GetID() int {
	_ = "STUB: not implemented"

	// GetName returns the value of Name.
	return 0
}

func (s *PetCreateOwner) GetName() string {
	_ = "STUB: not implemented"

	// GetAge returns the value of Age.
	return ""
}

func (s *PetCreateOwner) GetAge() int {
	_ = "STUB: not implemented"

	// SetID sets the value of ID.
	return 0
}

func (s *PetCreateOwner) SetID(val int) {
	_ = "STUB: not implemented"

	// SetName sets the value of Name.
	return
}

func (s *PetCreateOwner) SetName(val string) {
	_ = "STUB: not implemented"

	// SetAge sets the value of Age.
	return
}

func (s *PetCreateOwner) SetAge(val int) {
	_ = "STUB: not implemented"

	// Ref: #/components/schemas/Pet_FriendsCreate
	return
}

type PetFriendsCreate struct {
	ID       int         `json:"id"`
	Name     string      `json:"name"`
	Weight   OptInt      `json:"weight"`
	Birthday OptDateTime `json:"birthday"`
}

// GetID returns the value of ID.
func (s *PetFriendsCreate) GetID() int {
	_ = "STUB: not implemented"

	// GetName returns the value of Name.
	return 0
}

func (s *PetFriendsCreate) GetName() string {
	_ = "STUB: not implemented"

	// GetWeight returns the value of Weight.
	return ""
}

func (s *PetFriendsCreate) GetWeight() OptInt {
	_ = "STUB: not implemented"

	// GetBirthday returns the value of Birthday.
	return *new(OptInt)
}

func (s *PetFriendsCreate) GetBirthday() OptDateTime {
	_ = "STUB: not implemented"

	// SetID sets the value of ID.
	return *new(OptDateTime)
}

func (s *PetFriendsCreate) SetID(val int) {
	_ = "STUB: not implemented"

	// SetName sets the value of Name.
	return
}

func (s *PetFriendsCreate) SetName(val string) {
	_ = "STUB: not implemented"

	// SetWeight sets the value of Weight.
	return
}

func (s *PetFriendsCreate) SetWeight(val OptInt) {
	_ = "STUB: not implemented"

	// SetBirthday sets the value of Birthday.
	return
}

func (s *PetFriendsCreate) SetBirthday(val OptDateTime) { _ = "STUB: not implemented"; return }

func (*PetFriendsCreate) createPetFriendsRes() {
	_ = "STUB: not implemented"

	// Ref: #/components/schemas/Pet_FriendsList
	return
}

type PetFriendsList struct {
	ID       int         `json:"id"`
	Name     string      `json:"name"`
	Weight   OptInt      `json:"weight"`
	Birthday OptDateTime `json:"birthday"`
}

// GetID returns the value of ID.
func (s *PetFriendsList) GetID() int {
	_ = "STUB: not implemented"

	// GetName returns the value of Name.
	return 0
}

func (s *PetFriendsList) GetName() string {
	_ = "STUB: not implemented"

	// GetWeight returns the value of Weight.
	return ""
}

func (s *PetFriendsList) GetWeight() OptInt {
	_ = "STUB: not implemented"

	// GetBirthday returns the value of Birthday.
	return *new(OptInt)
}

func (s *PetFriendsList) GetBirthday() OptDateTime {
	_ = "STUB: not implemented"

	// SetID sets the value of ID.
	return *new(OptDateTime)
}

func (s *PetFriendsList) SetID(val int) {
	_ = "STUB: not implemented"

	// SetName sets the value of Name.
	return
}

func (s *PetFriendsList) SetName(val string) {
	_ = "STUB: not implemented"

	// SetWeight sets the value of Weight.
	return
}

func (s *PetFriendsList) SetWeight(val OptInt) {
	_ = "STUB: not implemented"

	// SetBirthday sets the value of Birthday.
	return
}

func (s *PetFriendsList) SetBirthday(val OptDateTime) {
	_ = "STUB: not implemented"

	// Ref: #/components/schemas/PetList
	return
}

type PetList struct {
	ID       int         `json:"id"`
	Name     string      `json:"name"`
	Weight   OptInt      `json:"weight"`
	Birthday OptDateTime `json:"birthday"`
}

// GetID returns the value of ID.
func (s *PetList) GetID() int {
	_ = "STUB: not implemented"

	// GetName returns the value of Name.
	return 0
}

func (s *PetList) GetName() string {
	_ = "STUB: not implemented"

	// GetWeight returns the value of Weight.
	return ""
}

func (s *PetList) GetWeight() OptInt {
	_ = "STUB: not implemented"

	// GetBirthday returns the value of Birthday.
	return *new(OptInt)
}

func (s *PetList) GetBirthday() OptDateTime {
	_ = "STUB: not implemented"

	// SetID sets the value of ID.
	return *new(OptDateTime)
}

func (s *PetList) SetID(val int) {
	_ = "STUB: not implemented"

	// SetName sets the value of Name.
	return
}

func (s *PetList) SetName(val string) {
	_ = "STUB: not implemented"

	// SetWeight sets the value of Weight.
	return
}

func (s *PetList) SetWeight(val OptInt) {
	_ = "STUB: not implemented"

	// SetBirthday sets the value of Birthday.
	return
}

func (s *PetList) SetBirthday(val OptDateTime) {
	_ = "STUB: not implemented"

	// Ref: #/components/schemas/Pet_OwnerCreate
	return
}

type PetOwnerCreate struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
	Age  int    `json:"age"`
}

// GetID returns the value of ID.
func (s *PetOwnerCreate) GetID() int {
	_ = "STUB: not implemented"

	// GetName returns the value of Name.
	return 0
}

func (s *PetOwnerCreate) GetName() string {
	_ = "STUB: not implemented"

	// GetAge returns the value of Age.
	return ""
}

func (s *PetOwnerCreate) GetAge() int {
	_ = "STUB: not implemented"

	// SetID sets the value of ID.
	return 0
}

func (s *PetOwnerCreate) SetID(val int) {
	_ = "STUB: not implemented"

	// SetName sets the value of Name.
	return
}

func (s *PetOwnerCreate) SetName(val string) {
	_ = "STUB: not implemented"

	// SetAge sets the value of Age.
	return
}

func (s *PetOwnerCreate) SetAge(val int) { _ = "STUB: not implemented"; return }

func (*PetOwnerCreate) createPetOwnerRes() {
	_ = "STUB: not implemented"

	// Ref: #/components/schemas/Pet_OwnerRead
	return
}

type PetOwnerRead struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
	Age  int    `json:"age"`
}

// GetID returns the value of ID.
func (s *PetOwnerRead) GetID() int {
	_ = "STUB: not implemented"

	// GetName returns the value of Name.
	return 0
}

func (s *PetOwnerRead) GetName() string {
	_ = "STUB: not implemented"

	// GetAge returns the value of Age.
	return ""
}

func (s *PetOwnerRead) GetAge() int {
	_ = "STUB: not implemented"

	// SetID sets the value of ID.
	return 0
}

func (s *PetOwnerRead) SetID(val int) {
	_ = "STUB: not implemented"

	// SetName sets the value of Name.
	return
}

func (s *PetOwnerRead) SetName(val string) {
	_ = "STUB: not implemented"

	// SetAge sets the value of Age.
	return
}

func (s *PetOwnerRead) SetAge(val int) { _ = "STUB: not implemented"; return }

func (*PetOwnerRead) readPetOwnerRes() {
	_ = "STUB: not implemented"

	// Ref: #/components/schemas/PetRead
	return
}

type PetRead struct {
	ID       int         `json:"id"`
	Name     string      `json:"name"`
	Weight   OptInt      `json:"weight"`
	Birthday OptDateTime `json:"birthday"`
}

// GetID returns the value of ID.
func (s *PetRead) GetID() int {
	_ = "STUB: not implemented"

	// GetName returns the value of Name.
	return 0
}

func (s *PetRead) GetName() string {
	_ = "STUB: not implemented"

	// GetWeight returns the value of Weight.
	return ""
}

func (s *PetRead) GetWeight() OptInt {
	_ = "STUB: not implemented"

	// GetBirthday returns the value of Birthday.
	return *new(OptInt)
}

func (s *PetRead) GetBirthday() OptDateTime {
	_ = "STUB: not implemented"

	// SetID sets the value of ID.
	return *new(OptDateTime)
}

func (s *PetRead) SetID(val int) {
	_ = "STUB: not implemented"

	// SetName sets the value of Name.
	return
}

func (s *PetRead) SetName(val string) {
	_ = "STUB: not implemented"

	// SetWeight sets the value of Weight.
	return
}

func (s *PetRead) SetWeight(val OptInt) {
	_ = "STUB: not implemented"

	// SetBirthday sets the value of Birthday.
	return
}

func (s *PetRead) SetBirthday(val OptDateTime) { _ = "STUB: not implemented"; return }

func (*PetRead) readPetRes() {
	_ = "STUB: not implemented"

	// Ref: #/components/schemas/PetUpdate
	return
}

type PetUpdate struct {
	ID       int         `json:"id"`
	Name     string      `json:"name"`
	Weight   OptInt      `json:"weight"`
	Birthday OptDateTime `json:"birthday"`
}

// GetID returns the value of ID.
func (s *PetUpdate) GetID() int {
	_ = "STUB: not implemented"

	// GetName returns the value of Name.
	return 0
}

func (s *PetUpdate) GetName() string {
	_ = "STUB: not implemented"

	// GetWeight returns the value of Weight.
	return ""
}

func (s *PetUpdate) GetWeight() OptInt {
	_ = "STUB: not implemented"

	// GetBirthday returns the value of Birthday.
	return *new(OptInt)
}

func (s *PetUpdate) GetBirthday() OptDateTime {
	_ = "STUB: not implemented"

	// SetID sets the value of ID.
	return *new(OptDateTime)
}

func (s *PetUpdate) SetID(val int) {
	_ = "STUB: not implemented"

	// SetName sets the value of Name.
	return
}

func (s *PetUpdate) SetName(val string) {
	_ = "STUB: not implemented"

	// SetWeight sets the value of Weight.
	return
}

func (s *PetUpdate) SetWeight(val OptInt) {
	_ = "STUB: not implemented"

	// SetBirthday sets the value of Birthday.
	return
}

func (s *PetUpdate) SetBirthday(val OptDateTime) { _ = "STUB: not implemented"; return }

func (*PetUpdate) updatePetRes() { _ = "STUB: not implemented"; return }

type R400 struct {
	Code   int    `json:"code"`
	Status string `json:"status"`
}

// GetCode returns the value of Code.
func (s *R400) GetCode() int {
	_ = "STUB: not implemented"

	// GetStatus returns the value of Status.
	return 0
}

func (s *R400) GetStatus() string {
	_ = "STUB: not implemented"

	// SetCode sets the value of Code.
	return ""
}

func (s *R400) SetCode(val int) {
	_ = "STUB: not implemented"

	// SetStatus sets the value of Status.
	return
}

func (s *R400) SetStatus(val string) { _ = "STUB: not implemented"; return }

func (*R400) createPetCategoriesRes() { _ = "STUB: not implemented"; return }
func (*R400) createPetFriendsRes()    { _ = "STUB: not implemented"; return }
func (*R400) createPetOwnerRes()      { _ = "STUB: not implemented"; return }
func (*R400) createPetRes()           { _ = "STUB: not implemented"; return }
func (*R400) deletePetOwnerRes()      { _ = "STUB: not implemented"; return }
func (*R400) deletePetRes()           { _ = "STUB: not implemented"; return }
func (*R400) listPetCategoriesRes()   { _ = "STUB: not implemented"; return }
func (*R400) listPetFriendsRes()      { _ = "STUB: not implemented"; return }
func (*R400) listPetRes()             { _ = "STUB: not implemented"; return }
func (*R400) readPetOwnerRes()        { _ = "STUB: not implemented"; return }
func (*R400) readPetRes()             { _ = "STUB: not implemented"; return }
func (*R400) updatePetRes()           { _ = "STUB: not implemented"; return }

type R404 struct {
	Code   int    `json:"code"`
	Status string `json:"status"`
}

// GetCode returns the value of Code.
func (s *R404) GetCode() int {
	_ = "STUB: not implemented"

	// GetStatus returns the value of Status.
	return 0
}

func (s *R404) GetStatus() string {
	_ = "STUB: not implemented"

	// SetCode sets the value of Code.
	return ""
}

func (s *R404) SetCode(val int) {
	_ = "STUB: not implemented"

	// SetStatus sets the value of Status.
	return
}

func (s *R404) SetStatus(val string) { _ = "STUB: not implemented"; return }

func (*R404) deletePetOwnerRes()    { _ = "STUB: not implemented"; return }
func (*R404) deletePetRes()         { _ = "STUB: not implemented"; return }
func (*R404) listPetCategoriesRes() { _ = "STUB: not implemented"; return }
func (*R404) listPetFriendsRes()    { _ = "STUB: not implemented"; return }
func (*R404) listPetRes()           { _ = "STUB: not implemented"; return }
func (*R404) readPetOwnerRes()      { _ = "STUB: not implemented"; return }
func (*R404) readPetRes()           { _ = "STUB: not implemented"; return }
func (*R404) updatePetRes()         { _ = "STUB: not implemented"; return }

type R409 struct {
	Code   int    `json:"code"`
	Status string `json:"status"`
}

// GetCode returns the value of Code.
func (s *R409) GetCode() int {
	_ = "STUB: not implemented"

	// GetStatus returns the value of Status.
	return 0
}

func (s *R409) GetStatus() string {
	_ = "STUB: not implemented"

	// SetCode sets the value of Code.
	return ""
}

func (s *R409) SetCode(val int) {
	_ = "STUB: not implemented"

	// SetStatus sets the value of Status.
	return
}

func (s *R409) SetStatus(val string) { _ = "STUB: not implemented"; return }

func (*R409) createPetCategoriesRes() { _ = "STUB: not implemented"; return }
func (*R409) createPetFriendsRes()    { _ = "STUB: not implemented"; return }
func (*R409) createPetOwnerRes()      { _ = "STUB: not implemented"; return }
func (*R409) createPetRes()           { _ = "STUB: not implemented"; return }

type R500 struct {
	Code   int    `json:"code"`
	Status string `json:"status"`
}

// GetCode returns the value of Code.
func (s *R500) GetCode() int {
	_ = "STUB: not implemented"

	// GetStatus returns the value of Status.
	return 0
}

func (s *R500) GetStatus() string {
	_ = "STUB: not implemented"

	// SetCode sets the value of Code.
	return ""
}

func (s *R500) SetCode(val int) {
	_ = "STUB: not implemented"

	// SetStatus sets the value of Status.
	return
}

func (s *R500) SetStatus(val string) { _ = "STUB: not implemented"; return }

func (*R500) createPetCategoriesRes() { _ = "STUB: not implemented"; return }
func (*R500) createPetFriendsRes()    { _ = "STUB: not implemented"; return }
func (*R500) createPetOwnerRes()      { _ = "STUB: not implemented"; return }
func (*R500) createPetRes()           { _ = "STUB: not implemented"; return }
func (*R500) deletePetOwnerRes()      { _ = "STUB: not implemented"; return }
func (*R500) deletePetRes()           { _ = "STUB: not implemented"; return }
func (*R500) listPetCategoriesRes()   { _ = "STUB: not implemented"; return }
func (*R500) listPetFriendsRes()      { _ = "STUB: not implemented"; return }
func (*R500) listPetRes()             { _ = "STUB: not implemented"; return }
func (*R500) readPetOwnerRes()        { _ = "STUB: not implemented"; return }
func (*R500) readPetRes()             { _ = "STUB: not implemented"; return }
func (*R500) updatePetRes()           { _ = "STUB: not implemented"; return }

type UpdatePetReq struct {
	Name       string      `json:"name"`
	Weight     OptInt      `json:"weight"`
	Birthday   OptDateTime `json:"birthday"`
	Categories []int       `json:"categories"`
	Owner      int         `json:"owner"`
	Friends    []int       `json:"friends"`
}

// GetName returns the value of Name.
func (s *UpdatePetReq) GetName() string {
	_ = "STUB: not implemented"

	// GetWeight returns the value of Weight.
	return ""
}

func (s *UpdatePetReq) GetWeight() OptInt {
	_ = "STUB: not implemented"

	// GetBirthday returns the value of Birthday.
	return *new(OptInt)
}

func (s *UpdatePetReq) GetBirthday() OptDateTime {
	_ = "STUB: not implemented"

	// GetCategories returns the value of Categories.
	return *new(OptDateTime)
}

func (s *UpdatePetReq) GetCategories() []int { _ = "STUB: not implemented"; return nil }

// GetOwner returns the value of Owner.
func (s *UpdatePetReq) GetOwner() int {
	_ = "STUB: not implemented"

	// GetFriends returns the value of Friends.
	return 0
}

func (s *UpdatePetReq) GetFriends() []int {
	_ = "STUB: not implemented"

	// SetName sets the value of Name.
	return nil
}

func (s *UpdatePetReq) SetName(val string) {
	_ = "STUB: not implemented"

	// SetWeight sets the value of Weight.
	return
}

func (s *UpdatePetReq) SetWeight(val OptInt) {
	_ = "STUB: not implemented"

	// SetBirthday sets the value of Birthday.
	return
}

func (s *UpdatePetReq) SetBirthday(val OptDateTime) {
	_ = "STUB: not implemented"

	// SetCategories sets the value of Categories.
	return
}

func (s *UpdatePetReq) SetCategories(val []int) {
	_ = "STUB: not implemented"

	// SetOwner sets the value of Owner.
	return
}

func (s *UpdatePetReq) SetOwner(val int) {
	_ = "STUB: not implemented"

	// SetFriends sets the value of Friends.
	return
}

func (s *UpdatePetReq) SetFriends(val []int) { _ = "STUB: not implemented"; return }
