// Code generated by ogen, DO NOT EDIT.

package api

func (s AnyValue) Validate() error { _ = "STUB: not implemented"; return nil }

// no validation needed

// no validation needed

// no validation needed

// no validation needed

func (s *ArrayValue) Validate() error { _ = "STUB: not implemented"; return nil }

func (s Attributes) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *DoubleValue) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *KeyValue) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *KvlistValue) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *ScopeTags) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *TagNamesV2) Validate() error { _ = "STUB: not implemented"; return nil }

func (s TagScope) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *TempoSpan) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *TempoSpanSet) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *TraceSearchMetadata) Validate() error { _ = "STUB: not implemented"; return nil }

func (s *Traces) Validate() error { _ = "STUB: not implemented"; return nil }
