// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/url"
)

func trimTrailingSlashes(u *url.URL) { _ = "STUB: not implemented"; return }

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// BuildInfo invokes buildInfo operation.
	//
	// Returns Tempo buildinfo, in the same format as Prometheus `/api/v1/status/buildinfo`.
	// Used by Grafana to check Tempo API version.
	//
	// GET /api/status/buildinfo
	BuildInfo(ctx context.Context) (*PrometheusVersion, error)
	// Echo invokes echo operation.
	//
	// Echo request for testing, issued by Grafana.
	//
	// GET /api/echo
	Echo(ctx context.Context) (EchoOK, error)
	// Search invokes search operation.
	//
	// Execute TraceQL query.
	//
	// GET /api/search
	Search(ctx context.Context, params SearchParams) (*Traces, error)
	// SearchTagValues invokes searchTagValues operation.
	//
	// This endpoint retrieves all discovered values for the given tag, which can be used in search.
	//
	// GET /api/search/tag/{tag_name}/values
	SearchTagValues(ctx context.Context, params SearchTagValuesParams) (*TagValues, error)
	// SearchTagValuesV2 invokes searchTagValuesV2 operation.
	//
	// This endpoint retrieves all discovered values and their data types for the given TraceQL
	// identifier.
	//
	// GET /api/v2/search/tag/{attribute_selector}/values
	SearchTagValuesV2(ctx context.Context, params SearchTagValuesV2Params) (*TagValuesV2, error)
	// SearchTags invokes searchTags operation.
	//
	// This endpoint retrieves all discovered tag names that can be used in search.
	//
	// GET /api/search/tags
	SearchTags(ctx context.Context, params SearchTagsParams) (*TagNames, error)
	// SearchTagsV2 invokes searchTagsV2 operation.
	//
	// This endpoint retrieves all discovered tag names that can be used in search.
	//
	// GET /api/v2/search/tags
	SearchTagsV2(ctx context.Context, params SearchTagsV2Params) (*TagNamesV2, error)
	// TraceByID invokes traceByID operation.
	//
	// Querying traces by id.
	//
	// GET /api/traces/{traceID}
	TraceByID(ctx context.Context, params TraceByIDParams) (TraceByIDRes, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	baseClient
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, opts ...ClientOption) (*Client, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

func (c *Client) requestURL(ctx context.Context) *url.URL { _ = "STUB: not implemented"; return nil }

// BuildInfo invokes buildInfo operation.
//
// Returns Tempo buildinfo, in the same format as Prometheus `/api/v1/status/buildinfo`.
// Used by Grafana to check Tempo API version.
//
// GET /api/status/buildinfo
func (c *Client) BuildInfo(ctx context.Context) (*PrometheusVersion, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) sendBuildInfo(ctx context.Context) (res *PrometheusVersion, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// Echo invokes echo operation.
//
// Echo request for testing, issued by Grafana.
//
// GET /api/echo
func (c *Client) Echo(ctx context.Context) (EchoOK, error) {
	_ = "STUB: not implemented"
	return *new(EchoOK), nil
}

func (c *Client) sendEcho(ctx context.Context) (res EchoOK, err error) {
	_ = "STUB: not implemented"
	return *new(EchoOK), nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// Search invokes search operation.
//
// Execute TraceQL query.
//
// GET /api/search
func (c *Client) Search(ctx context.Context, params SearchParams) (*Traces, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) sendSearch(ctx context.Context, params SearchParams) (res *Traces, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// Encode "q" parameter.

// Encode "tags" parameter.

// Encode "minDuration" parameter.

// Encode "maxDuration" parameter.

// Encode "limit" parameter.

// Encode "start" parameter.

// Encode "end" parameter.

// Encode "spss" parameter.

// SearchTagValues invokes searchTagValues operation.
//
// This endpoint retrieves all discovered values for the given tag, which can be used in search.
//
// GET /api/search/tag/{tag_name}/values
func (c *Client) SearchTagValues(ctx context.Context, params SearchTagValuesParams) (*TagValues, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) sendSearchTagValues(ctx context.Context, params SearchTagValuesParams) (res *TagValues, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// Encode "tag_name" parameter.

// Encode "q" parameter.

// Encode "start" parameter.

// Encode "end" parameter.

// SearchTagValuesV2 invokes searchTagValuesV2 operation.
//
// This endpoint retrieves all discovered values and their data types for the given TraceQL
// identifier.
//
// GET /api/v2/search/tag/{attribute_selector}/values
func (c *Client) SearchTagValuesV2(ctx context.Context, params SearchTagValuesV2Params) (*TagValuesV2, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) sendSearchTagValuesV2(ctx context.Context, params SearchTagValuesV2Params) (res *TagValuesV2, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// Encode "attribute_selector" parameter.

// Encode "q" parameter.

// Encode "start" parameter.

// Encode "end" parameter.

// SearchTags invokes searchTags operation.
//
// This endpoint retrieves all discovered tag names that can be used in search.
//
// GET /api/search/tags
func (c *Client) SearchTags(ctx context.Context, params SearchTagsParams) (*TagNames, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) sendSearchTags(ctx context.Context, params SearchTagsParams) (res *TagNames, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// Encode "scope" parameter.

// Encode "start" parameter.

// Encode "end" parameter.

// SearchTagsV2 invokes searchTagsV2 operation.
//
// This endpoint retrieves all discovered tag names that can be used in search.
//
// GET /api/v2/search/tags
func (c *Client) SearchTagsV2(ctx context.Context, params SearchTagsV2Params) (*TagNamesV2, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) sendSearchTagsV2(ctx context.Context, params SearchTagsV2Params) (res *TagNamesV2, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// Encode "scope" parameter.

// Encode "start" parameter.

// Encode "end" parameter.

// TraceByID invokes traceByID operation.
//
// Querying traces by id.
//
// GET /api/traces/{traceID}
func (c *Client) TraceByID(ctx context.Context, params TraceByIDParams) (TraceByIDRes, error) {
	_ = "STUB: not implemented"
	return *new(TraceByIDRes), nil
}

func (c *Client) sendTraceByID(ctx context.Context, params TraceByIDParams) (res TraceByIDRes, err error) {
	_ = "STUB: not implemented"
	return *new(TraceByIDRes), nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// Encode "traceID" parameter.

// Encode "start" parameter.

// Encode "end" parameter.
