// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// MarketBondsGet implements GET /market/bonds operation.
//
// Получение списка облигаций.
//
// GET /market/bonds
func (UnimplementedHandler) MarketBondsGet(ctx context.Context) (r MarketBondsGetRes, _ error) {
	_ = "STUB: not implemented"
	return *new(MarketBondsGetRes), nil
}

// MarketCandlesGet implements GET /market/candles operation.
//
// Получение исторических свечей по FIGI.
//
// GET /market/candles
func (UnimplementedHandler) MarketCandlesGet(ctx context.Context, params MarketCandlesGetParams) (r MarketCandlesGetRes, _ error) {
	_ = "STUB: not implemented"
	return *new(MarketCandlesGetRes), nil
}

// MarketCurrenciesGet implements GET /market/currencies operation.
//
// Получение списка валютных пар.
//
// GET /market/currencies
func (UnimplementedHandler) MarketCurrenciesGet(ctx context.Context) (r MarketCurrenciesGetRes, _ error) {
	_ = "STUB: not implemented"
	return *new(MarketCurrenciesGetRes), nil
}

// MarketEtfsGet implements GET /market/etfs operation.
//
// Получение списка ETF.
//
// GET /market/etfs
func (UnimplementedHandler) MarketEtfsGet(ctx context.Context) (r MarketEtfsGetRes, _ error) {
	_ = "STUB: not implemented"
	return *new(MarketEtfsGetRes), nil
}

// MarketOrderbookGet implements GET /market/orderbook operation.
//
// Получение стакана по FIGI.
//
// GET /market/orderbook
func (UnimplementedHandler) MarketOrderbookGet(ctx context.Context, params MarketOrderbookGetParams) (r MarketOrderbookGetRes, _ error) {
	_ = "STUB: not implemented"
	return *new(MarketOrderbookGetRes), nil
}

// MarketSearchByFigiGet implements GET /market/search/by-figi operation.
//
// Получение инструмента по FIGI.
//
// GET /market/search/by-figi
func (UnimplementedHandler) MarketSearchByFigiGet(ctx context.Context, params MarketSearchByFigiGetParams) (r MarketSearchByFigiGetRes, _ error) {
	_ = "STUB: not implemented"
	return *new(MarketSearchByFigiGetRes), nil
}

// MarketSearchByTickerGet implements GET /market/search/by-ticker operation.
//
// Получение инструмента по тикеру.
//
// GET /market/search/by-ticker
func (UnimplementedHandler) MarketSearchByTickerGet(ctx context.Context, params MarketSearchByTickerGetParams) (r MarketSearchByTickerGetRes, _ error) {
	_ = "STUB: not implemented"
	return *new(MarketSearchByTickerGetRes), nil
}

// MarketStocksGet implements GET /market/stocks operation.
//
// Получение списка акций.
//
// GET /market/stocks
func (UnimplementedHandler) MarketStocksGet(ctx context.Context) (r MarketStocksGetRes, _ error) {
	_ = "STUB: not implemented"
	return *new(MarketStocksGetRes), nil
}

// OperationsGet implements GET /operations operation.
//
// Получение списка операций.
//
// GET /operations
func (UnimplementedHandler) OperationsGet(ctx context.Context, params OperationsGetParams) (r OperationsGetRes, _ error) {
	_ = "STUB: not implemented"
	return *new(OperationsGetRes), nil
}

// OrdersCancelPost implements POST /orders/cancel operation.
//
// Отмена заявки.
//
// POST /orders/cancel
func (UnimplementedHandler) OrdersCancelPost(ctx context.Context, params OrdersCancelPostParams) (r OrdersCancelPostRes, _ error) {
	_ = "STUB: not implemented"
	return *new(OrdersCancelPostRes), nil
}

// OrdersGet implements GET /orders operation.
//
// Получение списка активных заявок.
//
// GET /orders
func (UnimplementedHandler) OrdersGet(ctx context.Context, params OrdersGetParams) (r OrdersGetRes, _ error) {
	_ = "STUB: not implemented"
	return *new(OrdersGetRes), nil
}

// OrdersLimitOrderPost implements POST /orders/limit-order operation.
//
// Создание лимитной заявки.
//
// POST /orders/limit-order
func (UnimplementedHandler) OrdersLimitOrderPost(ctx context.Context, req *LimitOrderRequest, params OrdersLimitOrderPostParams) (r OrdersLimitOrderPostRes, _ error) {
	_ = "STUB: not implemented"
	return *new(OrdersLimitOrderPostRes), nil
}

// OrdersMarketOrderPost implements POST /orders/market-order operation.
//
// Создание рыночной заявки.
//
// POST /orders/market-order
func (UnimplementedHandler) OrdersMarketOrderPost(ctx context.Context, req *MarketOrderRequest, params OrdersMarketOrderPostParams) (r OrdersMarketOrderPostRes, _ error) {
	_ = "STUB: not implemented"
	return *new(OrdersMarketOrderPostRes), nil
}

// PortfolioCurrenciesGet implements GET /portfolio/currencies operation.
//
// Получение валютных активов клиента.
//
// GET /portfolio/currencies
func (UnimplementedHandler) PortfolioCurrenciesGet(ctx context.Context, params PortfolioCurrenciesGetParams) (r PortfolioCurrenciesGetRes, _ error) {
	_ = "STUB: not implemented"
	return *new(PortfolioCurrenciesGetRes), nil
}

// PortfolioGet implements GET /portfolio operation.
//
// Получение портфеля клиента.
//
// GET /portfolio
func (UnimplementedHandler) PortfolioGet(ctx context.Context, params PortfolioGetParams) (r PortfolioGetRes, _ error) {
	_ = "STUB: not implemented"
	return *new(PortfolioGetRes), nil
}

// SandboxClearPost implements POST /sandbox/clear operation.
//
// Удаление всех позиций клиента.
//
// POST /sandbox/clear
func (UnimplementedHandler) SandboxClearPost(ctx context.Context, params SandboxClearPostParams) (r SandboxClearPostRes, _ error) {
	_ = "STUB: not implemented"
	return *new(SandboxClearPostRes), nil
}

// SandboxCurrenciesBalancePost implements POST /sandbox/currencies/balance operation.
//
// Выставление баланса по валютным позициям.
//
// POST /sandbox/currencies/balance
func (UnimplementedHandler) SandboxCurrenciesBalancePost(ctx context.Context, req *SandboxSetCurrencyBalanceRequest, params SandboxCurrenciesBalancePostParams) (r SandboxCurrenciesBalancePostRes, _ error) {
	_ = "STUB: not implemented"
	return *new(SandboxCurrenciesBalancePostRes), nil
}

// SandboxPositionsBalancePost implements POST /sandbox/positions/balance operation.
//
// Выставление баланса по инструментным позициям.
//
// POST /sandbox/positions/balance
func (UnimplementedHandler) SandboxPositionsBalancePost(ctx context.Context, req *SandboxSetPositionBalanceRequest, params SandboxPositionsBalancePostParams) (r SandboxPositionsBalancePostRes, _ error) {
	_ = "STUB: not implemented"
	return *new(SandboxPositionsBalancePostRes), nil
}

// SandboxRegisterPost implements POST /sandbox/register operation.
//
// Создание счета и валютных позиций для клиента.
//
// POST /sandbox/register
func (UnimplementedHandler) SandboxRegisterPost(ctx context.Context, req OptSandboxRegisterRequest) (r SandboxRegisterPostRes, _ error) {
	_ = "STUB: not implemented"
	return *new(SandboxRegisterPostRes), nil
}

// SandboxRemovePost implements POST /sandbox/remove operation.
//
// Удаление счета клиента.
//
// POST /sandbox/remove
func (UnimplementedHandler) SandboxRemovePost(ctx context.Context, params SandboxRemovePostParams) (r SandboxRemovePostRes, _ error) {
	_ = "STUB: not implemented"
	return *new(SandboxRemovePostRes), nil
}

// UserAccountsGet implements GET /user/accounts operation.
//
// Получение брокерских счетов клиента.
//
// GET /user/accounts
func (UnimplementedHandler) UserAccountsGet(ctx context.Context) (r UserAccountsGetRes, _ error) {
	_ = "STUB: not implemented"
	return *new(UserAccountsGetRes), nil
}
