// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/jx"
)

// Encode implements json.Marshaler.
func (s *ChatCompletionRequestMessage) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *ChatCompletionRequestMessage) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfChatCompletionRequestMessage = [3]string{
	0: "role",
	1: "content",
	2: "name",
}

// Decode decodes ChatCompletionRequestMessage from json.
func (s *ChatCompletionRequestMessage) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *ChatCompletionRequestMessage) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *ChatCompletionRequestMessage) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes ChatCompletionRequestMessageRole as json.
func (s ChatCompletionRequestMessageRole) Encode(e *jx.Encoder) {
	_ = "STUB: not implemented"

	// Decode decodes ChatCompletionRequestMessageRole from json.
	return
}

func (s *ChatCompletionRequestMessageRole) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Try to use constant string.

// MarshalJSON implements stdjson.Marshaler.
func (s ChatCompletionRequestMessageRole) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *ChatCompletionRequestMessageRole) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *ChatCompletionResponseMessage) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *ChatCompletionResponseMessage) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfChatCompletionResponseMessage = [2]string{
	0: "role",
	1: "content",
}

// Decode decodes ChatCompletionResponseMessage from json.
func (s *ChatCompletionResponseMessage) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *ChatCompletionResponseMessage) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *ChatCompletionResponseMessage) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes ChatCompletionResponseMessageRole as json.
func (s ChatCompletionResponseMessageRole) Encode(e *jx.Encoder) {
	_ = "STUB: not implemented"

	// Decode decodes ChatCompletionResponseMessageRole from json.
	return
}

func (s *ChatCompletionResponseMessageRole) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Try to use constant string.

// MarshalJSON implements stdjson.Marshaler.
func (s ChatCompletionResponseMessageRole) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *ChatCompletionResponseMessageRole) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateAnswerRequest) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateAnswerRequest) encodeFields(e *jx.Encoder) { _ = "STUB: not implemented"; return }

var jsonFieldsNameOfCreateAnswerRequest = [18]string{
	0:  "model",
	1:  "question",
	2:  "examples",
	3:  "examples_context",
	4:  "documents",
	5:  "file",
	6:  "search_model",
	7:  "max_rerank",
	8:  "temperature",
	9:  "logprobs",
	10: "max_tokens",
	11: "stop",
	12: "n",
	13: "logit_bias",
	14: "return_metadata",
	15: "return_prompt",
	16: "expand",
	17: "user",
}

// Decode decodes CreateAnswerRequest from json.
func (s *CreateAnswerRequest) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateAnswerRequest) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateAnswerRequest) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateAnswerRequestLogitBias) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateAnswerRequestLogitBias) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfCreateAnswerRequestLogitBias = [0]string{}

// Decode decodes CreateAnswerRequestLogitBias from json.
func (s *CreateAnswerRequestLogitBias) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateAnswerRequestLogitBias) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateAnswerRequestLogitBias) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes CreateAnswerRequestStop as json.
func (s CreateAnswerRequestStop) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes CreateAnswerRequestStop from json.
func (s *CreateAnswerRequestStop) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Sum type type_discriminator.

// MarshalJSON implements stdjson.Marshaler.
func (s CreateAnswerRequestStop) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateAnswerRequestStop) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateAnswerResponse) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateAnswerResponse) encodeFields(e *jx.Encoder) { _ = "STUB: not implemented"; return }

var jsonFieldsNameOfCreateAnswerResponse = [6]string{
	0: "object",
	1: "model",
	2: "search_model",
	3: "completion",
	4: "answers",
	5: "selected_documents",
}

// Decode decodes CreateAnswerResponse from json.
func (s *CreateAnswerResponse) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateAnswerResponse) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateAnswerResponse) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateAnswerResponseSelectedDocumentsItem) Encode(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

// encodeFields encodes fields.
func (s *CreateAnswerResponseSelectedDocumentsItem) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfCreateAnswerResponseSelectedDocumentsItem = [2]string{
	0: "document",
	1: "text",
}

// Decode decodes CreateAnswerResponseSelectedDocumentsItem from json.
func (s *CreateAnswerResponseSelectedDocumentsItem) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateAnswerResponseSelectedDocumentsItem) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateAnswerResponseSelectedDocumentsItem) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateChatCompletionRequest) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateChatCompletionRequest) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfCreateChatCompletionRequest = [12]string{
	0:  "model",
	1:  "messages",
	2:  "temperature",
	3:  "top_p",
	4:  "n",
	5:  "stream",
	6:  "stop",
	7:  "max_tokens",
	8:  "presence_penalty",
	9:  "frequency_penalty",
	10: "logit_bias",
	11: "user",
}

// Decode decodes CreateChatCompletionRequest from json.
func (s *CreateChatCompletionRequest) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateChatCompletionRequest) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateChatCompletionRequest) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateChatCompletionRequestLogitBias) Encode(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

// encodeFields encodes fields.
func (s *CreateChatCompletionRequestLogitBias) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfCreateChatCompletionRequestLogitBias = [0]string{}

// Decode decodes CreateChatCompletionRequestLogitBias from json.
func (s *CreateChatCompletionRequestLogitBias) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateChatCompletionRequestLogitBias) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateChatCompletionRequestLogitBias) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes CreateChatCompletionRequestStop as json.
func (s CreateChatCompletionRequestStop) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes CreateChatCompletionRequestStop from json.
func (s *CreateChatCompletionRequestStop) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Sum type type_discriminator.

// MarshalJSON implements stdjson.Marshaler.
func (s CreateChatCompletionRequestStop) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateChatCompletionRequestStop) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateChatCompletionResponse) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateChatCompletionResponse) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfCreateChatCompletionResponse = [6]string{
	0: "id",
	1: "object",
	2: "created",
	3: "model",
	4: "choices",
	5: "usage",
}

// Decode decodes CreateChatCompletionResponse from json.
func (s *CreateChatCompletionResponse) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateChatCompletionResponse) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateChatCompletionResponse) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateChatCompletionResponseChoicesItem) Encode(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

// encodeFields encodes fields.
func (s *CreateChatCompletionResponseChoicesItem) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfCreateChatCompletionResponseChoicesItem = [3]string{
	0: "index",
	1: "message",
	2: "finish_reason",
}

// Decode decodes CreateChatCompletionResponseChoicesItem from json.
func (s *CreateChatCompletionResponseChoicesItem) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateChatCompletionResponseChoicesItem) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateChatCompletionResponseChoicesItem) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateChatCompletionResponseUsage) Encode(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

// encodeFields encodes fields.
func (s *CreateChatCompletionResponseUsage) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfCreateChatCompletionResponseUsage = [3]string{
	0: "prompt_tokens",
	1: "completion_tokens",
	2: "total_tokens",
}

// Decode decodes CreateChatCompletionResponseUsage from json.
func (s *CreateChatCompletionResponseUsage) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateChatCompletionResponseUsage) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateChatCompletionResponseUsage) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateClassificationRequest) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateClassificationRequest) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfCreateClassificationRequest = [14]string{
	0:  "model",
	1:  "query",
	2:  "examples",
	3:  "file",
	4:  "labels",
	5:  "search_model",
	6:  "temperature",
	7:  "logprobs",
	8:  "max_examples",
	9:  "logit_bias",
	10: "return_prompt",
	11: "return_metadata",
	12: "expand",
	13: "user",
}

// Decode decodes CreateClassificationRequest from json.
func (s *CreateClassificationRequest) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateClassificationRequest) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateClassificationRequest) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateClassificationRequestLogitBias) Encode(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

// encodeFields encodes fields.
func (s *CreateClassificationRequestLogitBias) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfCreateClassificationRequestLogitBias = [0]string{}

// Decode decodes CreateClassificationRequestLogitBias from json.
func (s *CreateClassificationRequestLogitBias) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateClassificationRequestLogitBias) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateClassificationRequestLogitBias) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateClassificationResponse) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateClassificationResponse) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfCreateClassificationResponse = [6]string{
	0: "object",
	1: "model",
	2: "search_model",
	3: "completion",
	4: "label",
	5: "selected_examples",
}

// Decode decodes CreateClassificationResponse from json.
func (s *CreateClassificationResponse) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateClassificationResponse) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateClassificationResponse) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateClassificationResponseSelectedExamplesItem) Encode(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

// encodeFields encodes fields.
func (s *CreateClassificationResponseSelectedExamplesItem) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfCreateClassificationResponseSelectedExamplesItem = [3]string{
	0: "document",
	1: "text",
	2: "label",
}

// Decode decodes CreateClassificationResponseSelectedExamplesItem from json.
func (s *CreateClassificationResponseSelectedExamplesItem) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateClassificationResponseSelectedExamplesItem) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateClassificationResponseSelectedExamplesItem) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateCompletionRequest) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateCompletionRequest) encodeFields(e *jx.Encoder) { _ = "STUB: not implemented"; return }

var jsonFieldsNameOfCreateCompletionRequest = [16]string{
	0:  "model",
	1:  "prompt",
	2:  "suffix",
	3:  "max_tokens",
	4:  "temperature",
	5:  "top_p",
	6:  "n",
	7:  "stream",
	8:  "logprobs",
	9:  "echo",
	10: "stop",
	11: "presence_penalty",
	12: "frequency_penalty",
	13: "best_of",
	14: "logit_bias",
	15: "user",
}

// Decode decodes CreateCompletionRequest from json.
func (s *CreateCompletionRequest) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateCompletionRequest) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateCompletionRequest) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateCompletionRequestLogitBias) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateCompletionRequestLogitBias) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfCreateCompletionRequestLogitBias = [0]string{}

// Decode decodes CreateCompletionRequestLogitBias from json.
func (s *CreateCompletionRequestLogitBias) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateCompletionRequestLogitBias) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateCompletionRequestLogitBias) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes CreateCompletionRequestPrompt as json.
func (s CreateCompletionRequestPrompt) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes CreateCompletionRequestPrompt from json.
func (s *CreateCompletionRequestPrompt) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Sum type type_discriminator.

// MarshalJSON implements stdjson.Marshaler.
func (s CreateCompletionRequestPrompt) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateCompletionRequestPrompt) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes CreateCompletionRequestStop as json.
func (s CreateCompletionRequestStop) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes CreateCompletionRequestStop from json.
func (s *CreateCompletionRequestStop) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Sum type type_discriminator.

// MarshalJSON implements stdjson.Marshaler.
func (s CreateCompletionRequestStop) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateCompletionRequestStop) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateCompletionResponse) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateCompletionResponse) encodeFields(e *jx.Encoder) { _ = "STUB: not implemented"; return }

var jsonFieldsNameOfCreateCompletionResponse = [6]string{
	0: "id",
	1: "object",
	2: "created",
	3: "model",
	4: "choices",
	5: "usage",
}

// Decode decodes CreateCompletionResponse from json.
func (s *CreateCompletionResponse) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateCompletionResponse) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateCompletionResponse) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateCompletionResponseChoicesItem) Encode(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

// encodeFields encodes fields.
func (s *CreateCompletionResponseChoicesItem) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfCreateCompletionResponseChoicesItem = [4]string{
	0: "text",
	1: "index",
	2: "logprobs",
	3: "finish_reason",
}

// Decode decodes CreateCompletionResponseChoicesItem from json.
func (s *CreateCompletionResponseChoicesItem) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateCompletionResponseChoicesItem) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateCompletionResponseChoicesItem) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateCompletionResponseChoicesItemLogprobs) Encode(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

// encodeFields encodes fields.
func (s *CreateCompletionResponseChoicesItemLogprobs) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfCreateCompletionResponseChoicesItemLogprobs = [4]string{
	0: "tokens",
	1: "token_logprobs",
	2: "top_logprobs",
	3: "text_offset",
}

// Decode decodes CreateCompletionResponseChoicesItemLogprobs from json.
func (s *CreateCompletionResponseChoicesItemLogprobs) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateCompletionResponseChoicesItemLogprobs) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateCompletionResponseChoicesItemLogprobs) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateCompletionResponseChoicesItemLogprobsTopLogprobsItem) Encode(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

// encodeFields encodes fields.
func (s *CreateCompletionResponseChoicesItemLogprobsTopLogprobsItem) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfCreateCompletionResponseChoicesItemLogprobsTopLogprobsItem = [0]string{}

// Decode decodes CreateCompletionResponseChoicesItemLogprobsTopLogprobsItem from json.
func (s *CreateCompletionResponseChoicesItemLogprobsTopLogprobsItem) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateCompletionResponseChoicesItemLogprobsTopLogprobsItem) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateCompletionResponseChoicesItemLogprobsTopLogprobsItem) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateCompletionResponseUsage) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateCompletionResponseUsage) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfCreateCompletionResponseUsage = [3]string{
	0: "prompt_tokens",
	1: "completion_tokens",
	2: "total_tokens",
}

// Decode decodes CreateCompletionResponseUsage from json.
func (s *CreateCompletionResponseUsage) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateCompletionResponseUsage) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateCompletionResponseUsage) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateEditRequest) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateEditRequest) encodeFields(e *jx.Encoder) { _ = "STUB: not implemented"; return }

var jsonFieldsNameOfCreateEditRequest = [6]string{
	0: "model",
	1: "input",
	2: "instruction",
	3: "n",
	4: "temperature",
	5: "top_p",
}

// Decode decodes CreateEditRequest from json.
func (s *CreateEditRequest) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateEditRequest) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateEditRequest) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

// Encode implements json.Marshaler.
func (s *CreateEditResponse) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateEditResponse) encodeFields(e *jx.Encoder) { _ = "STUB: not implemented"; return }

var jsonFieldsNameOfCreateEditResponse = [4]string{
	0: "object",
	1: "created",
	2: "choices",
	3: "usage",
}

// Decode decodes CreateEditResponse from json.
func (s *CreateEditResponse) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateEditResponse) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateEditResponse) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateEditResponseChoicesItem) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateEditResponseChoicesItem) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfCreateEditResponseChoicesItem = [4]string{
	0: "text",
	1: "index",
	2: "logprobs",
	3: "finish_reason",
}

// Decode decodes CreateEditResponseChoicesItem from json.
func (s *CreateEditResponseChoicesItem) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateEditResponseChoicesItem) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateEditResponseChoicesItem) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateEditResponseChoicesItemLogprobs) Encode(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

// encodeFields encodes fields.
func (s *CreateEditResponseChoicesItemLogprobs) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfCreateEditResponseChoicesItemLogprobs = [4]string{
	0: "tokens",
	1: "token_logprobs",
	2: "top_logprobs",
	3: "text_offset",
}

// Decode decodes CreateEditResponseChoicesItemLogprobs from json.
func (s *CreateEditResponseChoicesItemLogprobs) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateEditResponseChoicesItemLogprobs) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateEditResponseChoicesItemLogprobs) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateEditResponseChoicesItemLogprobsTopLogprobsItem) Encode(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

// encodeFields encodes fields.
func (s *CreateEditResponseChoicesItemLogprobsTopLogprobsItem) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfCreateEditResponseChoicesItemLogprobsTopLogprobsItem = [0]string{}

// Decode decodes CreateEditResponseChoicesItemLogprobsTopLogprobsItem from json.
func (s *CreateEditResponseChoicesItemLogprobsTopLogprobsItem) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateEditResponseChoicesItemLogprobsTopLogprobsItem) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateEditResponseChoicesItemLogprobsTopLogprobsItem) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateEditResponseUsage) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateEditResponseUsage) encodeFields(e *jx.Encoder) { _ = "STUB: not implemented"; return }

var jsonFieldsNameOfCreateEditResponseUsage = [3]string{
	0: "prompt_tokens",
	1: "completion_tokens",
	2: "total_tokens",
}

// Decode decodes CreateEditResponseUsage from json.
func (s *CreateEditResponseUsage) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateEditResponseUsage) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateEditResponseUsage) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateEmbeddingRequest) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateEmbeddingRequest) encodeFields(e *jx.Encoder) { _ = "STUB: not implemented"; return }

var jsonFieldsNameOfCreateEmbeddingRequest = [3]string{
	0: "model",
	1: "input",
	2: "user",
}

// Decode decodes CreateEmbeddingRequest from json.
func (s *CreateEmbeddingRequest) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateEmbeddingRequest) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateEmbeddingRequest) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes CreateEmbeddingRequestInput as json.
func (s CreateEmbeddingRequestInput) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes CreateEmbeddingRequestInput from json.
func (s *CreateEmbeddingRequestInput) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Sum type type_discriminator.

// MarshalJSON implements stdjson.Marshaler.
func (s CreateEmbeddingRequestInput) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateEmbeddingRequestInput) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateEmbeddingResponse) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateEmbeddingResponse) encodeFields(e *jx.Encoder) { _ = "STUB: not implemented"; return }

var jsonFieldsNameOfCreateEmbeddingResponse = [4]string{
	0: "object",
	1: "model",
	2: "data",
	3: "usage",
}

// Decode decodes CreateEmbeddingResponse from json.
func (s *CreateEmbeddingResponse) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateEmbeddingResponse) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateEmbeddingResponse) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateEmbeddingResponseDataItem) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateEmbeddingResponseDataItem) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfCreateEmbeddingResponseDataItem = [3]string{
	0: "index",
	1: "object",
	2: "embedding",
}

// Decode decodes CreateEmbeddingResponseDataItem from json.
func (s *CreateEmbeddingResponseDataItem) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateEmbeddingResponseDataItem) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateEmbeddingResponseDataItem) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateEmbeddingResponseUsage) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateEmbeddingResponseUsage) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfCreateEmbeddingResponseUsage = [2]string{
	0: "prompt_tokens",
	1: "total_tokens",
}

// Decode decodes CreateEmbeddingResponseUsage from json.
func (s *CreateEmbeddingResponseUsage) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateEmbeddingResponseUsage) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateEmbeddingResponseUsage) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateFineTuneRequest) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateFineTuneRequest) encodeFields(e *jx.Encoder) { _ = "STUB: not implemented"; return }

var jsonFieldsNameOfCreateFineTuneRequest = [12]string{
	0:  "training_file",
	1:  "validation_file",
	2:  "model",
	3:  "n_epochs",
	4:  "batch_size",
	5:  "learning_rate_multiplier",
	6:  "prompt_loss_weight",
	7:  "compute_classification_metrics",
	8:  "classification_n_classes",
	9:  "classification_positive_class",
	10: "classification_betas",
	11: "suffix",
}

// Decode decodes CreateFineTuneRequest from json.
func (s *CreateFineTuneRequest) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateFineTuneRequest) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateFineTuneRequest) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateImageRequest) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateImageRequest) encodeFields(e *jx.Encoder) { _ = "STUB: not implemented"; return }

var jsonFieldsNameOfCreateImageRequest = [5]string{
	0: "prompt",
	1: "n",
	2: "size",
	3: "response_format",
	4: "user",
}

// Decode decodes CreateImageRequest from json.
func (s *CreateImageRequest) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateImageRequest) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateImageRequest) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes CreateImageRequestResponseFormat as json.
func (s CreateImageRequestResponseFormat) Encode(e *jx.Encoder) {
	_ = "STUB: not implemented"

	// Decode decodes CreateImageRequestResponseFormat from json.
	return
}

func (s *CreateImageRequestResponseFormat) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Try to use constant string.

// MarshalJSON implements stdjson.Marshaler.
func (s CreateImageRequestResponseFormat) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateImageRequestResponseFormat) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes CreateImageRequestSize as json.
func (s CreateImageRequestSize) Encode(e *jx.Encoder) {
	_ = "STUB: not implemented"

	// Decode decodes CreateImageRequestSize from json.
	return
}

func (s *CreateImageRequestSize) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// Try to use constant string.

// MarshalJSON implements stdjson.Marshaler.
func (s CreateImageRequestSize) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateImageRequestSize) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateModerationRequest) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateModerationRequest) encodeFields(e *jx.Encoder) { _ = "STUB: not implemented"; return }

var jsonFieldsNameOfCreateModerationRequest = [2]string{
	0: "input",
	1: "model",
}

// Decode decodes CreateModerationRequest from json.
func (s *CreateModerationRequest) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateModerationRequest) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateModerationRequest) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes CreateModerationRequestInput as json.
func (s CreateModerationRequestInput) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes CreateModerationRequestInput from json.
func (s *CreateModerationRequestInput) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Sum type type_discriminator.

// MarshalJSON implements stdjson.Marshaler.
func (s CreateModerationRequestInput) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateModerationRequestInput) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateModerationResponse) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateModerationResponse) encodeFields(e *jx.Encoder) { _ = "STUB: not implemented"; return }

var jsonFieldsNameOfCreateModerationResponse = [3]string{
	0: "id",
	1: "model",
	2: "results",
}

// Decode decodes CreateModerationResponse from json.
func (s *CreateModerationResponse) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateModerationResponse) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateModerationResponse) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateModerationResponseResultsItem) Encode(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

// encodeFields encodes fields.
func (s *CreateModerationResponseResultsItem) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfCreateModerationResponseResultsItem = [3]string{
	0: "flagged",
	1: "categories",
	2: "category_scores",
}

// Decode decodes CreateModerationResponseResultsItem from json.
func (s *CreateModerationResponseResultsItem) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateModerationResponseResultsItem) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateModerationResponseResultsItem) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateModerationResponseResultsItemCategories) Encode(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

// encodeFields encodes fields.
func (s *CreateModerationResponseResultsItemCategories) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfCreateModerationResponseResultsItemCategories = [7]string{
	0: "hate",
	1: "hate/threatening",
	2: "self-harm",
	3: "sexual",
	4: "sexual/minors",
	5: "violence",
	6: "violence/graphic",
}

// Decode decodes CreateModerationResponseResultsItemCategories from json.
func (s *CreateModerationResponseResultsItemCategories) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateModerationResponseResultsItemCategories) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateModerationResponseResultsItemCategories) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateModerationResponseResultsItemCategoryScores) Encode(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

// encodeFields encodes fields.
func (s *CreateModerationResponseResultsItemCategoryScores) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfCreateModerationResponseResultsItemCategoryScores = [7]string{
	0: "hate",
	1: "hate/threatening",
	2: "self-harm",
	3: "sexual",
	4: "sexual/minors",
	5: "violence",
	6: "violence/graphic",
}

// Decode decodes CreateModerationResponseResultsItemCategoryScores from json.
func (s *CreateModerationResponseResultsItemCategoryScores) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateModerationResponseResultsItemCategoryScores) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateModerationResponseResultsItemCategoryScores) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateSearchRequest) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateSearchRequest) encodeFields(e *jx.Encoder) { _ = "STUB: not implemented"; return }

var jsonFieldsNameOfCreateSearchRequest = [6]string{
	0: "query",
	1: "documents",
	2: "file",
	3: "max_rerank",
	4: "return_metadata",
	5: "user",
}

// Decode decodes CreateSearchRequest from json.
func (s *CreateSearchRequest) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateSearchRequest) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateSearchRequest) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateSearchResponse) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateSearchResponse) encodeFields(e *jx.Encoder) { _ = "STUB: not implemented"; return }

var jsonFieldsNameOfCreateSearchResponse = [3]string{
	0: "object",
	1: "model",
	2: "data",
}

// Decode decodes CreateSearchResponse from json.
func (s *CreateSearchResponse) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateSearchResponse) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateSearchResponse) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateSearchResponseDataItem) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateSearchResponseDataItem) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfCreateSearchResponseDataItem = [3]string{
	0: "object",
	1: "document",
	2: "score",
}

// Decode decodes CreateSearchResponseDataItem from json.
func (s *CreateSearchResponseDataItem) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateSearchResponseDataItem) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateSearchResponseDataItem) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateTranscriptionResponse) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateTranscriptionResponse) encodeFields(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

var jsonFieldsNameOfCreateTranscriptionResponse = [1]string{
	0: "text",
}

// Decode decodes CreateTranscriptionResponse from json.
func (s *CreateTranscriptionResponse) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateTranscriptionResponse) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateTranscriptionResponse) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *CreateTranslationResponse) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *CreateTranslationResponse) encodeFields(e *jx.Encoder) { _ = "STUB: not implemented"; return }

var jsonFieldsNameOfCreateTranslationResponse = [1]string{
	0: "text",
}

// Decode decodes CreateTranslationResponse from json.
func (s *CreateTranslationResponse) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateTranslationResponse) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateTranslationResponse) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *DeleteFileResponse) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *DeleteFileResponse) encodeFields(e *jx.Encoder) { _ = "STUB: not implemented"; return }

var jsonFieldsNameOfDeleteFileResponse = [3]string{
	0: "id",
	1: "object",
	2: "deleted",
}

// Decode decodes DeleteFileResponse from json.
func (s *DeleteFileResponse) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *DeleteFileResponse) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *DeleteFileResponse) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *DeleteModelResponse) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *DeleteModelResponse) encodeFields(e *jx.Encoder) { _ = "STUB: not implemented"; return }

var jsonFieldsNameOfDeleteModelResponse = [3]string{
	0: "id",
	1: "object",
	2: "deleted",
}

// Decode decodes DeleteModelResponse from json.
func (s *DeleteModelResponse) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *DeleteModelResponse) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *DeleteModelResponse) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes Engine as json.
func (s Engine) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes Engine from json.
func (s *Engine) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// MarshalJSON implements stdjson.Marshaler.
func (s Engine) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *Engine) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

// Encode encodes FineTune as json.
func (s FineTune) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes FineTune from json.
func (s *FineTune) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// MarshalJSON implements stdjson.Marshaler.
func (s FineTune) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *FineTune) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

// Encode encodes FineTuneEvent as json.
func (s FineTuneEvent) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes FineTuneEvent from json.
func (s *FineTuneEvent) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// MarshalJSON implements stdjson.Marshaler.
func (s FineTuneEvent) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *FineTuneEvent) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

// Encode encodes ImagesResponse as json.
func (s ImagesResponse) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes ImagesResponse from json.
func (s *ImagesResponse) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// MarshalJSON implements stdjson.Marshaler.
func (s ImagesResponse) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *ImagesResponse) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

// Encode implements json.Marshaler.
func (s *ListEnginesResponse) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *ListEnginesResponse) encodeFields(e *jx.Encoder) { _ = "STUB: not implemented"; return }

var jsonFieldsNameOfListEnginesResponse = [2]string{
	0: "object",
	1: "data",
}

// Decode decodes ListEnginesResponse from json.
func (s *ListEnginesResponse) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *ListEnginesResponse) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *ListEnginesResponse) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *ListFilesResponse) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *ListFilesResponse) encodeFields(e *jx.Encoder) { _ = "STUB: not implemented"; return }

var jsonFieldsNameOfListFilesResponse = [2]string{
	0: "object",
	1: "data",
}

// Decode decodes ListFilesResponse from json.
func (s *ListFilesResponse) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *ListFilesResponse) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *ListFilesResponse) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

// Encode implements json.Marshaler.
func (s *ListFineTuneEventsResponse) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *ListFineTuneEventsResponse) encodeFields(e *jx.Encoder) { _ = "STUB: not implemented"; return }

var jsonFieldsNameOfListFineTuneEventsResponse = [2]string{
	0: "object",
	1: "data",
}

// Decode decodes ListFineTuneEventsResponse from json.
func (s *ListFineTuneEventsResponse) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *ListFineTuneEventsResponse) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *ListFineTuneEventsResponse) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *ListFineTunesResponse) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *ListFineTunesResponse) encodeFields(e *jx.Encoder) { _ = "STUB: not implemented"; return }

var jsonFieldsNameOfListFineTunesResponse = [2]string{
	0: "object",
	1: "data",
}

// Decode decodes ListFineTunesResponse from json.
func (s *ListFineTunesResponse) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *ListFineTunesResponse) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *ListFineTunesResponse) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode implements json.Marshaler.
func (s *ListModelsResponse) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *ListModelsResponse) encodeFields(e *jx.Encoder) { _ = "STUB: not implemented"; return }

var jsonFieldsNameOfListModelsResponse = [2]string{
	0: "object",
	1: "data",
}

// Decode decodes ListModelsResponse from json.
func (s *ListModelsResponse) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *ListModelsResponse) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *ListModelsResponse) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes Model as json.
func (s Model) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes Model from json.
func (s *Model) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// MarshalJSON implements stdjson.Marshaler.
func (s Model) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *Model) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

// Encode encodes OpenAIFile as json.
func (s OpenAIFile) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes OpenAIFile from json.
func (s *OpenAIFile) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// MarshalJSON implements stdjson.Marshaler.
func (s OpenAIFile) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OpenAIFile) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

// Encode encodes ChatCompletionResponseMessage as json.
func (o OptChatCompletionResponseMessage) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes ChatCompletionResponseMessage from json.
func (o *OptChatCompletionResponseMessage) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptChatCompletionResponseMessage) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptChatCompletionResponseMessage) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes *CreateAnswerRequestLogitBias as json.
func (o OptCreateAnswerRequestLogitBias) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes *CreateAnswerRequestLogitBias from json.
func (o *OptCreateAnswerRequestLogitBias) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptCreateAnswerRequestLogitBias) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptCreateAnswerRequestLogitBias) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes *CreateChatCompletionRequestLogitBias as json.
func (o OptCreateChatCompletionRequestLogitBias) Encode(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

// Decode decodes *CreateChatCompletionRequestLogitBias from json.
func (o *OptCreateChatCompletionRequestLogitBias) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptCreateChatCompletionRequestLogitBias) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptCreateChatCompletionRequestLogitBias) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes CreateChatCompletionResponseUsage as json.
func (o OptCreateChatCompletionResponseUsage) Encode(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

// Decode decodes CreateChatCompletionResponseUsage from json.
func (o *OptCreateChatCompletionResponseUsage) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptCreateChatCompletionResponseUsage) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptCreateChatCompletionResponseUsage) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes *CreateClassificationRequestLogitBias as json.
func (o OptCreateClassificationRequestLogitBias) Encode(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

// Decode decodes *CreateClassificationRequestLogitBias from json.
func (o *OptCreateClassificationRequestLogitBias) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptCreateClassificationRequestLogitBias) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptCreateClassificationRequestLogitBias) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes *CreateCompletionRequestLogitBias as json.
func (o OptCreateCompletionRequestLogitBias) Encode(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

// Decode decodes *CreateCompletionRequestLogitBias from json.
func (o *OptCreateCompletionRequestLogitBias) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptCreateCompletionRequestLogitBias) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptCreateCompletionRequestLogitBias) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes CreateCompletionResponseUsage as json.
func (o OptCreateCompletionResponseUsage) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes CreateCompletionResponseUsage from json.
func (o *OptCreateCompletionResponseUsage) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptCreateCompletionResponseUsage) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptCreateCompletionResponseUsage) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes float64 as json.
func (o OptFloat64) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes float64 from json.
func (o *OptFloat64) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// MarshalJSON implements stdjson.Marshaler.
func (s OptFloat64) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptFloat64) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

// Encode encodes int as json.
func (o OptInt) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes int from json.
func (o *OptInt) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// MarshalJSON implements stdjson.Marshaler.
func (s OptInt) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptInt) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

// Encode encodes []jx.Raw as json.
func (o OptNilAnyArray) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes []jx.Raw from json.
func (o *OptNilAnyArray) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// MarshalJSON implements stdjson.Marshaler.
func (s OptNilAnyArray) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptNilAnyArray) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

// Encode encodes bool as json.
func (o OptNilBool) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes bool from json.
func (o *OptNilBool) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// MarshalJSON implements stdjson.Marshaler.
func (s OptNilBool) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptNilBool) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

// Encode encodes CreateAnswerRequestStop as json.
func (o OptNilCreateAnswerRequestStop) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes CreateAnswerRequestStop from json.
func (o *OptNilCreateAnswerRequestStop) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptNilCreateAnswerRequestStop) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptNilCreateAnswerRequestStop) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes CreateChatCompletionRequestStop as json.
func (o OptNilCreateChatCompletionRequestStop) Encode(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

// Decode decodes CreateChatCompletionRequestStop from json.
func (o *OptNilCreateChatCompletionRequestStop) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptNilCreateChatCompletionRequestStop) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptNilCreateChatCompletionRequestStop) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes CreateCompletionRequestPrompt as json.
func (o OptNilCreateCompletionRequestPrompt) Encode(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

// Decode decodes CreateCompletionRequestPrompt from json.
func (o *OptNilCreateCompletionRequestPrompt) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptNilCreateCompletionRequestPrompt) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptNilCreateCompletionRequestPrompt) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes CreateCompletionRequestStop as json.
func (o OptNilCreateCompletionRequestStop) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes CreateCompletionRequestStop from json.
func (o *OptNilCreateCompletionRequestStop) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptNilCreateCompletionRequestStop) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptNilCreateCompletionRequestStop) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes CreateCompletionResponseChoicesItemLogprobs as json.
func (o OptNilCreateCompletionResponseChoicesItemLogprobs) Encode(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

// Decode decodes CreateCompletionResponseChoicesItemLogprobs from json.
func (o *OptNilCreateCompletionResponseChoicesItemLogprobs) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptNilCreateCompletionResponseChoicesItemLogprobs) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptNilCreateCompletionResponseChoicesItemLogprobs) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes CreateEditResponseChoicesItemLogprobs as json.
func (o OptNilCreateEditResponseChoicesItemLogprobs) Encode(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

// Decode decodes CreateEditResponseChoicesItemLogprobs from json.
func (o *OptNilCreateEditResponseChoicesItemLogprobs) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptNilCreateEditResponseChoicesItemLogprobs) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptNilCreateEditResponseChoicesItemLogprobs) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes CreateImageRequestResponseFormat as json.
func (o OptNilCreateImageRequestResponseFormat) Encode(e *jx.Encoder) {
	_ = "STUB: not implemented"
	return
}

// Decode decodes CreateImageRequestResponseFormat from json.
func (o *OptNilCreateImageRequestResponseFormat) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptNilCreateImageRequestResponseFormat) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptNilCreateImageRequestResponseFormat) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes CreateImageRequestSize as json.
func (o OptNilCreateImageRequestSize) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes CreateImageRequestSize from json.
func (o *OptNilCreateImageRequestSize) Decode(d *jx.Decoder) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptNilCreateImageRequestSize) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptNilCreateImageRequestSize) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes float64 as json.
func (o OptNilFloat64) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes float64 from json.
func (o *OptNilFloat64) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// MarshalJSON implements stdjson.Marshaler.
func (s OptNilFloat64) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptNilFloat64) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

// Encode encodes []float64 as json.
func (o OptNilFloat64Array) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes []float64 from json.
func (o *OptNilFloat64Array) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// MarshalJSON implements stdjson.Marshaler.
func (s OptNilFloat64Array) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptNilFloat64Array) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes int as json.
func (o OptNilInt) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes int from json.
func (o *OptNilInt) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// MarshalJSON implements stdjson.Marshaler.
func (s OptNilInt) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptNilInt) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

// Encode encodes string as json.
func (o OptNilString) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes string from json.
func (o *OptNilString) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// MarshalJSON implements stdjson.Marshaler.
func (s OptNilString) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptNilString) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

// Encode encodes []string as json.
func (o OptNilStringArray) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes []string from json.
func (o *OptNilStringArray) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// MarshalJSON implements stdjson.Marshaler.
func (s OptNilStringArray) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptNilStringArray) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

// Encode encodes [][]string as json.
func (o OptNilStringArrayArray) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes [][]string from json.
func (o *OptNilStringArrayArray) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// MarshalJSON implements stdjson.Marshaler.
func (s OptNilStringArrayArray) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptNilStringArrayArray) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Encode encodes string as json.
func (o OptString) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes string from json.
func (o *OptString) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// MarshalJSON implements stdjson.Marshaler.
func (s OptString) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptString) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }
