// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"
)

type Alias time.Time

// NewOptAlias returns new OptAlias with value set to v.
func NewOptAlias(v Alias) OptAlias { _ = "STUB: not implemented"; return *new(OptAlias) }

// OptAlias is optional Alias.
type OptAlias struct {
	Value Alias
	Set   bool
}

// IsSet returns true if OptAlias was set.
func (o OptAlias) IsSet() bool {
	_ = "STUB: not implemented"

	// Reset unsets value.
	return false
}

func (o *OptAlias) Reset() { _ = "STUB: not implemented"; return }

// SetTo sets value to v.
func (o *OptAlias) SetTo(v Alias) { _ = "STUB: not implemented"; return }

// Get returns value and boolean that denotes whether value was set.
func (o OptAlias) Get() (v Alias, ok bool) { _ = "STUB: not implemented"; return *new(Alias), false }

// Or returns value if set, or given parameter if does not.
func (o OptAlias) Or(d Alias) Alias { _ = "STUB: not implemented"; return *new(Alias) }

// NewOptDate returns new OptDate with value set to v.
func NewOptDate(v time.Time) OptDate { _ = "STUB: not implemented"; return *new(OptDate) }

// OptDate is optional time.Time.
type OptDate struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDate was set.
func (o OptDate) IsSet() bool {
	_ = "STUB: not implemented"

	// Reset unsets value.
	return false
}

func (o *OptDate) Reset() { _ = "STUB: not implemented"; return }

// SetTo sets value to v.
func (o *OptDate) SetTo(v time.Time) { _ = "STUB: not implemented"; return }

// Get returns value and boolean that denotes whether value was set.
func (o OptDate) Get() (v time.Time, ok bool) {
	_ = "STUB: not implemented"
	return *new(time.Time), false
}

// Or returns value if set, or given parameter if does not.
func (o OptDate) Or(d time.Time) time.Time { _ = "STUB: not implemented"; return *new(time.Time) }

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime { _ = "STUB: not implemented"; return *new(OptDateTime) }

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool {
	_ = "STUB: not implemented"

	// Reset unsets value.
	return false
}

func (o *OptDateTime) Reset() { _ = "STUB: not implemented"; return }

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) { _ = "STUB: not implemented"; return }

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	_ = "STUB: not implemented"
	return *new(time.Time), false
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time { _ = "STUB: not implemented"; return *new(time.Time) }

// NewOptTime returns new OptTime with value set to v.
func NewOptTime(v time.Time) OptTime { _ = "STUB: not implemented"; return *new(OptTime) }

// OptTime is optional time.Time.
type OptTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptTime was set.
func (o OptTime) IsSet() bool {
	_ = "STUB: not implemented"

	// Reset unsets value.
	return false
}

func (o *OptTime) Reset() { _ = "STUB: not implemented"; return }

// SetTo sets value to v.
func (o *OptTime) SetTo(v time.Time) { _ = "STUB: not implemented"; return }

// Get returns value and boolean that denotes whether value was set.
func (o OptTime) Get() (v time.Time, ok bool) {
	_ = "STUB: not implemented"
	return *new(time.Time), false
}

// Or returns value if set, or given parameter if does not.
func (o OptTime) Or(d time.Time) time.Time { _ = "STUB: not implemented"; return *new(time.Time) }

type OptionalOK struct {
	Date     OptDate     `json:"date"`
	Time     OptTime     `json:"time"`
	DateTime OptDateTime `json:"dateTime"`
	Alias    OptAlias    `json:"alias"`
}

// GetDate returns the value of Date.
func (s *OptionalOK) GetDate() OptDate {
	_ = "STUB: not implemented"

	// GetTime returns the value of Time.
	return *new(OptDate)
}

func (s *OptionalOK) GetTime() OptTime {
	_ = "STUB: not implemented"

	// GetDateTime returns the value of DateTime.
	return *new(OptTime)
}

func (s *OptionalOK) GetDateTime() OptDateTime {
	_ = "STUB: not implemented"

	// GetAlias returns the value of Alias.
	return *new(OptDateTime)
}

func (s *OptionalOK) GetAlias() OptAlias {
	_ = "STUB: not implemented"

	// SetDate sets the value of Date.
	return *new(OptAlias)
}

func (s *OptionalOK) SetDate(val OptDate) {
	_ = "STUB: not implemented"

	// SetTime sets the value of Time.
	return
}

func (s *OptionalOK) SetTime(val OptTime) {
	_ = "STUB: not implemented"

	// SetDateTime sets the value of DateTime.
	return
}

func (s *OptionalOK) SetDateTime(val OptDateTime) {
	_ = "STUB: not implemented"

	// SetAlias sets the value of Alias.
	return
}

func (s *OptionalOK) SetAlias(val OptAlias) { _ = "STUB: not implemented"; return }

type RequiredOK struct {
	Date     time.Time `json:"date"`
	Time     time.Time `json:"time"`
	DateTime time.Time `json:"dateTime"`
	Alias    Alias     `json:"alias"`
}

// GetDate returns the value of Date.
func (s *RequiredOK) GetDate() time.Time {
	_ = "STUB: not implemented"

	// GetTime returns the value of Time.
	return *new(time.Time)
}

func (s *RequiredOK) GetTime() time.Time {
	_ = "STUB: not implemented"

	// GetDateTime returns the value of DateTime.
	return *new(time.Time)
}

func (s *RequiredOK) GetDateTime() time.Time {
	_ = "STUB: not implemented"

	// GetAlias returns the value of Alias.
	return *new(time.Time)
}

func (s *RequiredOK) GetAlias() Alias {
	_ = "STUB: not implemented"

	// SetDate sets the value of Date.
	return *new(Alias)
}

func (s *RequiredOK) SetDate(val time.Time) {
	_ = "STUB: not implemented"

	// SetTime sets the value of Time.
	return
}

func (s *RequiredOK) SetTime(val time.Time) {
	_ = "STUB: not implemented"

	// SetDateTime sets the value of DateTime.
	return
}

func (s *RequiredOK) SetDateTime(val time.Time) {
	_ = "STUB: not implemented"

	// SetAlias sets the value of Alias.
	return
}

func (s *RequiredOK) SetAlias(val Alias) { _ = "STUB: not implemented"; return }
