// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/go-faster/jx"
)

// Encode encodes Alias as json.
func (s Alias) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes Alias from json.
func (s *Alias) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// MarshalJSON implements stdjson.Marshaler.
func (s Alias) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *Alias) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

// Encode encodes Alias as json.
func (o OptAlias) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// Decode decodes Alias from json.
func (o *OptAlias) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// MarshalJSON implements stdjson.Marshaler.
func (s OptAlias) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptAlias) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

// Encode encodes time.Time as json.
func (o OptDate) Encode(e *jx.Encoder, format func(*jx.Encoder, time.Time)) {
	_ = "STUB: not implemented"
	return
}

// Decode decodes time.Time from json.
func (o *OptDate) Decode(d *jx.Decoder, format func(*jx.Decoder) (time.Time, error)) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptDate) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptDate) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

// Encode encodes time.Time as json.
func (o OptDateTime) Encode(e *jx.Encoder, format func(*jx.Encoder, time.Time)) {
	_ = "STUB: not implemented"
	return
}

// Decode decodes time.Time from json.
func (o *OptDateTime) Decode(d *jx.Decoder, format func(*jx.Decoder) (time.Time, error)) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptDateTime) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptDateTime) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

// Encode encodes time.Time as json.
func (o OptTime) Encode(e *jx.Encoder, format func(*jx.Encoder, time.Time)) {
	_ = "STUB: not implemented"
	return
}

// Decode decodes time.Time from json.
func (o *OptTime) Decode(d *jx.Decoder, format func(*jx.Decoder) (time.Time, error)) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptTime) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptTime) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

// Encode implements json.Marshaler.
func (s *OptionalOK) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *OptionalOK) encodeFields(e *jx.Encoder) { _ = "STUB: not implemented"; return }

var jsonFieldsNameOfOptionalOK = [4]string{
	0: "date",
	1: "time",
	2: "dateTime",
	3: "alias",
}

// Decode decodes OptionalOK from json.
func (s *OptionalOK) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// MarshalJSON implements stdjson.Marshaler.
func (s *OptionalOK) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptionalOK) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }

// Encode implements json.Marshaler.
func (s *RequiredOK) Encode(e *jx.Encoder) { _ = "STUB: not implemented"; return }

// encodeFields encodes fields.
func (s *RequiredOK) encodeFields(e *jx.Encoder) { _ = "STUB: not implemented"; return }

var jsonFieldsNameOfRequiredOK = [4]string{
	0: "date",
	1: "time",
	2: "dateTime",
	3: "alias",
}

// Decode decodes RequiredOK from json.
func (s *RequiredOK) Decode(d *jx.Decoder) error { _ = "STUB: not implemented"; return nil }

// Validate required fields.

// Mask only required fields and check equality to mask using XOR.
//
// If XOR result is not zero, result is not equal to expected, so some fields are missed.
// Bits of fields which would be set are actually bits of missed fields.

// Reset bit.

// MarshalJSON implements stdjson.Marshaler.
func (s *RequiredOK) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *RequiredOK) UnmarshalJSON(data []byte) error { _ = "STUB: not implemented"; return nil }
