// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"
)

var (
	rn3AllowedHeaders = map[string]string{
		"PUT": "Content-Type",
	}
	rn4AllowedHeaders = map[string]string{
		"PATCH": "Content-Type",
		"PUT":   "Content-Type",
	}
	rn5AllowedHeaders = map[string]string{
		"PATCH": "Content-Type",
	}
	rn19AllowedHeaders = map[string]string{
		"PUT": "Content-Type",
	}
	rn14AllowedHeaders = map[string]string{
		"PATCH": "Content-Type",
		"PUT":   "Content-Type",
	}
	rn22AllowedHeaders = map[string]string{
		"PUT": "Content-Type",
	}
	rn7AllowedHeaders = map[string]string{
		"PATCH": "Content-Type",
		"PUT":   "Content-Type",
	}
	rn23AllowedHeaders = map[string]string{
		"PUT": "Content-Type",
	}
	rn12AllowedHeaders = map[string]string{
		"PATCH": "Content-Type",
		"PUT":   "Content-Type",
	}
	rn11AllowedHeaders = map[string]string{
		"PUT": "Content-Type",
	}
	rn16AllowedHeaders = map[string]string{
		"PATCH": "Content-Type",
		"PUT":   "Content-Type",
	}
	rn1AllowedHeaders = map[string]string{
		"PUT": "Content-Type",
	}
	rn9AllowedHeaders = map[string]string{
		"PUT": "Content-Type",
	}
	rn17AllowedHeaders = map[string]string{
		"PATCH": "Content-Type",
	}
	rn21AllowedHeaders = map[string]string{
		"PUT": "Content-Type",
	}
)

func (s *Server) cutPrefix(path string) (string, bool) { _ = "STUB: not implemented"; return "", false }

// Prefix doesn't match.

// Cut prefix from the path.

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Static code generated router with unwrapped path search.

// Prefix: "/"

// Prefix: "actions"

// Leaf node.

// Prefix: "b"

// Prefix: "alloon"

// Prefix: "/statistics"

// Leaf node.

// Prefix: "oot-source"

// Leaf node.

// Prefix: "drives/"

// Param: "drive_id"
// Leaf parameter, slashes are prohibited

// Leaf node.

// Prefix: "logger"

// Leaf node.

// Prefix: "m"

// Prefix: "achine-config"

// Leaf node.

// Prefix: "etrics"

// Leaf node.

// Prefix: "mds"

// Prefix: "/config"

// Leaf node.

// Prefix: "network-interfaces/"

// Param: "iface_id"
// Leaf parameter, slashes are prohibited

// Leaf node.

// Prefix: "snapshot/"

// Prefix: "create"

// Leaf node.

// Prefix: "load"

// Leaf node.

// Prefix: "v"

// Prefix: "m"

// Prefix: "/config"

// Leaf node.

// Prefix: "sock"

// Leaf node.

// Route is route object.
type Route struct {
	name           string
	summary        string
	operationID    string
	operationGroup string
	pathPattern    string
	count          int
	args           [1]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	_ = "STUB: not implemented"

	// Summary returns OpenAPI summary.
	return ""
}

func (r Route) Summary() string {
	_ = "STUB: not implemented"

	// OperationID returns OpenAPI operationId.
	return ""
}

func (r Route) OperationID() string { _ = "STUB: not implemented"; return "" }

// OperationGroup returns the x-ogen-operation-group value.
func (r Route) OperationGroup() string { _ = "STUB: not implemented"; return "" }

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string { _ = "STUB: not implemented"; return "" }

// Args returns parsed arguments.
func (r Route) Args() []string { _ = "STUB: not implemented"; return nil }

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	_ = "STUB: not implemented"
	return *new(Route), false
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	_ = "STUB: not implemented"
	return *new(Route), false
}

// Static code generated router with unwrapped path search.

// Prefix: "/"

// Prefix: "actions"

// Leaf node.

// Prefix: "b"

// Prefix: "alloon"

// Prefix: "/statistics"

// Leaf node.

// Prefix: "oot-source"

// Leaf node.

// Prefix: "drives/"

// Param: "drive_id"
// Leaf parameter, slashes are prohibited

// Leaf node.

// Prefix: "logger"

// Leaf node.

// Prefix: "m"

// Prefix: "achine-config"

// Leaf node.

// Prefix: "etrics"

// Leaf node.

// Prefix: "mds"

// Prefix: "/config"

// Leaf node.

// Prefix: "network-interfaces/"

// Param: "iface_id"
// Leaf parameter, slashes are prohibited

// Leaf node.

// Prefix: "snapshot/"

// Prefix: "create"

// Leaf node.

// Prefix: "load"

// Leaf node.

// Prefix: "v"

// Prefix: "m"

// Prefix: "/config"

// Leaf node.

// Prefix: "sock"

// Leaf node.
