// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
)

type codeRecorder struct {
	http.ResponseWriter
	status int
}

func (c *codeRecorder) WriteHeader(status int) { _ = "STUB: not implemented"; return }

func (c *codeRecorder) Unwrap() http.ResponseWriter {
	_ = "STUB: not implemented"
	return *

	// handleCreateSnapshotRequest handles createSnapshot operation.
	//
	// Creates a snapshot of the microVM state. The microVM should be in the `Paused` state.
	//
	// PUT /snapshot/create
	new(http.ResponseWriter)
}

func (s *Server) handleCreateSnapshotRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleCreateSyncActionRequest handles createSyncAction operation.
//
// Creates a synchronous action.
//
// PUT /actions
func (s *Server) handleCreateSyncActionRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleDescribeBalloonConfigRequest handles describeBalloonConfig operation.
//
// Returns the current balloon device configuration.
//
// GET /balloon
func (s *Server) handleDescribeBalloonConfigRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleDescribeBalloonStatsRequest handles describeBalloonStats operation.
//
// Returns the latest balloon device statistics, only if enabled pre-boot.
//
// GET /balloon/statistics
func (s *Server) handleDescribeBalloonStatsRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleDescribeInstanceRequest handles describeInstance operation.
//
// Returns general information about an instance.
//
// GET /
func (s *Server) handleDescribeInstanceRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleGetExportVmConfigRequest handles getExportVmConfig operation.
//
// Gets configuration for all VM resources.
//
// GET /vm/config
func (s *Server) handleGetExportVmConfigRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleGetMachineConfigurationRequest handles getMachineConfiguration operation.
//
// Gets the machine configuration of the VM. When called before the PUT operation, it will return the
// default values for the vCPU count (=1), memory size (=128 MiB). By default Hyperthreading is
// disabled and there is no CPU Template.
//
// GET /machine-config
func (s *Server) handleGetMachineConfigurationRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleLoadSnapshotRequest handles loadSnapshot operation.
//
// Loads the microVM state from a snapshot. Only accepted on a fresh Firecracker process (before
// configuring any resource other than the Logger and Metrics).
//
// PUT /snapshot/load
func (s *Server) handleLoadSnapshotRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleMmdsConfigPutRequest handles PUT /mmds/config operation.
//
// Creates MMDS configuration to be used by the MMDS network stack.
//
// PUT /mmds/config
func (s *Server) handleMmdsConfigPutRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleMmdsGetRequest handles GET /mmds operation.
//
// Get the MMDS data store.
//
// GET /mmds
func (s *Server) handleMmdsGetRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleMmdsPatchRequest handles PATCH /mmds operation.
//
// Updates the MMDS data store.
//
// PATCH /mmds
func (s *Server) handleMmdsPatchRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handleMmdsPutRequest handles PUT /mmds operation.
//
// Creates a MMDS (Microvm Metadata Service) data store.
//
// PUT /mmds
func (s *Server) handleMmdsPutRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handlePatchBalloonRequest handles patchBalloon operation.
//
// Updates an existing balloon device, before or after machine startup. Will fail if update is not
// possible.
//
// PATCH /balloon
func (s *Server) handlePatchBalloonRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handlePatchBalloonStatsIntervalRequest handles patchBalloonStatsInterval operation.
//
// Updates an existing balloon device statistics interval, before or after machine startup. Will fail
// if update is not possible.
//
// PATCH /balloon/statistics
func (s *Server) handlePatchBalloonStatsIntervalRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handlePatchGuestDriveByIDRequest handles patchGuestDriveByID operation.
//
// Updates the properties of the drive with the ID specified by drive_id path parameter. Will fail if
// update is not possible.
//
// PATCH /drives/{drive_id}
func (s *Server) handlePatchGuestDriveByIDRequest(args [1]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handlePatchGuestNetworkInterfaceByIDRequest handles patchGuestNetworkInterfaceByID operation.
//
// Updates the rate limiters applied to a network interface.
//
// PATCH /network-interfaces/{iface_id}
func (s *Server) handlePatchGuestNetworkInterfaceByIDRequest(args [1]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handlePatchMachineConfigurationRequest handles patchMachineConfiguration operation.
//
// Partially updates the Virtual Machine Configuration with the specified input. If any of the
// parameters has an incorrect value, the whole update fails.
//
// PATCH /machine-config
func (s *Server) handlePatchMachineConfigurationRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handlePatchVmRequest handles patchVm operation.
//
// Sets the desired state (Paused or Resumed) for the microVM.
//
// PATCH /vm
func (s *Server) handlePatchVmRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handlePutBalloonRequest handles putBalloon operation.
//
// Creates a new balloon device if one does not already exist, otherwise updates it, before machine
// startup. This will fail after machine startup. Will fail if update is not possible.
//
// PUT /balloon
func (s *Server) handlePutBalloonRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handlePutGuestBootSourceRequest handles putGuestBootSource operation.
//
// Creates new boot source if one does not already exist, otherwise updates it. Will fail if update
// is not possible.
//
// PUT /boot-source
func (s *Server) handlePutGuestBootSourceRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handlePutGuestDriveByIDRequest handles putGuestDriveByID operation.
//
// Creates new drive with ID specified by drive_id path parameter. If a drive with the specified ID
// already exists, updates its state based on new input. Will fail if update is not possible.
//
// PUT /drives/{drive_id}
func (s *Server) handlePutGuestDriveByIDRequest(args [1]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handlePutGuestNetworkInterfaceByIDRequest handles putGuestNetworkInterfaceByID operation.
//
// Creates new network interface with ID specified by iface_id path parameter.
//
// PUT /network-interfaces/{iface_id}
func (s *Server) handlePutGuestNetworkInterfaceByIDRequest(args [1]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handlePutGuestVsockRequest handles putGuestVsock operation.
//
// The first call creates the device with the configuration specified in body. Subsequent calls will
// update the device configuration. May fail if update is not possible.
//
// PUT /vsock
func (s *Server) handlePutGuestVsockRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handlePutLoggerRequest handles putLogger operation.
//
// Initializes the logger by specifying a named pipe or a file for the logs output.
//
// PUT /logger
func (s *Server) handlePutLoggerRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handlePutMachineConfigurationRequest handles putMachineConfiguration operation.
//
// Updates the Virtual Machine Configuration with the specified input. Firecracker starts with
// default values for vCPU count (=1) and memory size (=128 MiB). With Hyperthreading enabled, the
// vCPU count is restricted to be 1 or an even number, otherwise there are no restrictions regarding
// the vCPU count. If any of the parameters has an incorrect value, the whole update fails.
//
// PUT /machine-config
func (s *Server) handlePutMachineConfigurationRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.

// handlePutMetricsRequest handles putMetrics operation.
//
// Initializes the metrics system by specifying a named pipe or a file for the metrics output.
//
// PUT /metrics
func (s *Server) handlePutMetricsRequest(args [0]string, argsEscaped bool, w http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// Add attributes from config.

// Start a span for this request.

// Add Labeler to context.

// Run stopwatch.

// Increment request counter.

// Use floating point division here for higher precision (instead of Millisecond method).

// https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status
// Span Status MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges,
// unless there was another error (e.g., network error receiving the response body; or 3xx codes with
// max redirects exceeded), in which case status MUST be set to Error.
