// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
)

func (s *Server) decodeCreateSnapshotRequest(r *http.Request) (
	req *SnapshotCreateParams,
	rawBody []byte,
	close func() error,
	rerr error,
) {
	_ = "STUB: not implemented"
	return nil, nil, nil, nil
}

// Close in reverse order, to match defer behavior.

// Reset the body to allow for downstream reading.

func (s *Server) decodeCreateSyncActionRequest(r *http.Request) (
	req *InstanceActionInfo,
	rawBody []byte,
	close func() error,
	rerr error,
) {
	_ = "STUB: not implemented"
	return nil, nil, nil, nil
}

// Close in reverse order, to match defer behavior.

// Reset the body to allow for downstream reading.

func (s *Server) decodeLoadSnapshotRequest(r *http.Request) (
	req *SnapshotLoadParams,
	rawBody []byte,
	close func() error,
	rerr error,
) {
	_ = "STUB: not implemented"
	return nil, nil, nil, nil
}

// Close in reverse order, to match defer behavior.

// Reset the body to allow for downstream reading.

func (s *Server) decodeMmdsConfigPutRequest(r *http.Request) (
	req *MmdsConfig,
	rawBody []byte,
	close func() error,
	rerr error,
) {
	_ = "STUB: not implemented"
	return nil, nil, nil, nil
}

// Close in reverse order, to match defer behavior.

// Reset the body to allow for downstream reading.

func (s *Server) decodeMmdsPatchRequest(r *http.Request) (
	req *MmdsPatchReq,
	rawBody []byte,
	close func() error,
	rerr error,
) {
	_ = "STUB: not implemented"
	return nil, nil, nil, nil
}

// Close in reverse order, to match defer behavior.

// Reset the body to allow for downstream reading.

func (s *Server) decodeMmdsPutRequest(r *http.Request) (
	req *MmdsPutReq,
	rawBody []byte,
	close func() error,
	rerr error,
) {
	_ = "STUB: not implemented"
	return nil, nil, nil, nil
}

// Close in reverse order, to match defer behavior.

// Reset the body to allow for downstream reading.

func (s *Server) decodePatchBalloonRequest(r *http.Request) (
	req *BalloonUpdate,
	rawBody []byte,
	close func() error,
	rerr error,
) {
	_ = "STUB: not implemented"
	return nil, nil, nil, nil
}

// Close in reverse order, to match defer behavior.

// Reset the body to allow for downstream reading.

func (s *Server) decodePatchBalloonStatsIntervalRequest(r *http.Request) (
	req *BalloonStatsUpdate,
	rawBody []byte,
	close func() error,
	rerr error,
) {
	_ = "STUB: not implemented"
	return nil, nil, nil, nil
}

// Close in reverse order, to match defer behavior.

// Reset the body to allow for downstream reading.

func (s *Server) decodePatchGuestDriveByIDRequest(r *http.Request) (
	req *PartialDrive,
	rawBody []byte,
	close func() error,
	rerr error,
) {
	_ = "STUB: not implemented"
	return nil, nil, nil, nil
}

// Close in reverse order, to match defer behavior.

// Reset the body to allow for downstream reading.

func (s *Server) decodePatchGuestNetworkInterfaceByIDRequest(r *http.Request) (
	req *PartialNetworkInterface,
	rawBody []byte,
	close func() error,
	rerr error,
) {
	_ = "STUB: not implemented"
	return nil, nil, nil, nil
}

// Close in reverse order, to match defer behavior.

// Reset the body to allow for downstream reading.

func (s *Server) decodePatchMachineConfigurationRequest(r *http.Request) (
	req OptMachineConfiguration,
	rawBody []byte,
	close func() error,
	rerr error,
) {
	_ = "STUB: not implemented"
	return *new(OptMachineConfiguration), nil, nil, nil
}

// Close in reverse order, to match defer behavior.

// Reset the body to allow for downstream reading.

func (s *Server) decodePatchVmRequest(r *http.Request) (
	req *VM,
	rawBody []byte,
	close func() error,
	rerr error,
) {
	_ = "STUB: not implemented"
	return nil, nil, nil, nil
}

// Close in reverse order, to match defer behavior.

// Reset the body to allow for downstream reading.

func (s *Server) decodePutBalloonRequest(r *http.Request) (
	req *Balloon,
	rawBody []byte,
	close func() error,
	rerr error,
) {
	_ = "STUB: not implemented"
	return nil, nil, nil, nil
}

// Close in reverse order, to match defer behavior.

// Reset the body to allow for downstream reading.

func (s *Server) decodePutGuestBootSourceRequest(r *http.Request) (
	req *BootSource,
	rawBody []byte,
	close func() error,
	rerr error,
) {
	_ = "STUB: not implemented"
	return nil, nil, nil, nil
}

// Close in reverse order, to match defer behavior.

// Reset the body to allow for downstream reading.

func (s *Server) decodePutGuestDriveByIDRequest(r *http.Request) (
	req *Drive,
	rawBody []byte,
	close func() error,
	rerr error,
) {
	_ = "STUB: not implemented"
	return nil, nil, nil, nil
}

// Close in reverse order, to match defer behavior.

// Reset the body to allow for downstream reading.

func (s *Server) decodePutGuestNetworkInterfaceByIDRequest(r *http.Request) (
	req *NetworkInterface,
	rawBody []byte,
	close func() error,
	rerr error,
) {
	_ = "STUB: not implemented"
	return nil, nil, nil, nil
}

// Close in reverse order, to match defer behavior.

// Reset the body to allow for downstream reading.

func (s *Server) decodePutGuestVsockRequest(r *http.Request) (
	req *Vsock,
	rawBody []byte,
	close func() error,
	rerr error,
) {
	_ = "STUB: not implemented"
	return nil, nil, nil, nil
}

// Close in reverse order, to match defer behavior.

// Reset the body to allow for downstream reading.

func (s *Server) decodePutLoggerRequest(r *http.Request) (
	req *Logger,
	rawBody []byte,
	close func() error,
	rerr error,
) {
	_ = "STUB: not implemented"
	return nil, nil, nil, nil
}

// Close in reverse order, to match defer behavior.

// Reset the body to allow for downstream reading.

func (s *Server) decodePutMachineConfigurationRequest(r *http.Request) (
	req OptMachineConfiguration,
	rawBody []byte,
	close func() error,
	rerr error,
) {
	_ = "STUB: not implemented"
	return *new(OptMachineConfiguration), nil, nil, nil
}

// Close in reverse order, to match defer behavior.

// Reset the body to allow for downstream reading.

func (s *Server) decodePutMetricsRequest(r *http.Request) (
	req *Metrics,
	rawBody []byte,
	close func() error,
	rerr error,
) {
	_ = "STUB: not implemented"
	return nil, nil, nil, nil
}

// Close in reverse order, to match defer behavior.

// Reset the body to allow for downstream reading.
