// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/google/uuid"
)

func (s *ErrorStatusCode) Error() string { _ = "STUB: not implemented"; return "" }

// Ref: #/components/schemas/Error
type Error struct {
	Error string `json:"error"`
}

// GetError returns the value of Error.
func (s *Error) GetError() string {
	_ = "STUB: not implemented"

	// SetError sets the value of Error.
	return ""
}

func (s *Error) SetError(val string) {
	_ = "STUB: not implemented"

	// ErrorStatusCode wraps Error with StatusCode.
	return
}

type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int { _ = "STUB: not implemented"; return 0 }

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	_ = "STUB: not implemented"

	// SetStatusCode sets the value of StatusCode.
	return *new(Error)
}

func (s *ErrorStatusCode) SetStatusCode(val int) {
	_ = "STUB: not implemented"

	// SetResponse sets the value of Response.
	return
}

func (s *ErrorStatusCode) SetResponse(val Error) { _ = "STUB: not implemented"; return }

func (*ErrorStatusCode) updateDeleteRes() { _ = "STUB: not implemented"; return }
func (*ErrorStatusCode) updateWebhookRes() {
	_ = "STUB: not implemented"

	// Ref: #/components/schemas/Event
	return
}

type Event struct {
	ID      uuid.UUID `json:"id"`
	Message string    `json:"message"`
}

// GetID returns the value of ID.
func (s *Event) GetID() uuid.UUID {
	_ = "STUB: not implemented"

	// GetMessage returns the value of Message.
	return *new(uuid.UUID)
}

func (s *Event) GetMessage() string {
	_ = "STUB: not implemented"

	// SetID sets the value of ID.
	return ""
}

func (s *Event) SetID(val uuid.UUID) {
	_ = "STUB: not implemented"

	// SetMessage sets the value of Message.
	return
}

func (s *Event) SetMessage(val string) {
	_ = "STUB: not implemented"

	// NewOptEvent returns new OptEvent with value set to v.
	return
}

func NewOptEvent(v Event) OptEvent { _ = "STUB: not implemented"; return *new(OptEvent) }

// OptEvent is optional Event.
type OptEvent struct {
	Value Event
	Set   bool
}

// IsSet returns true if OptEvent was set.
func (o OptEvent) IsSet() bool {
	_ = "STUB: not implemented"

	// Reset unsets value.
	return false
}

func (o *OptEvent) Reset() { _ = "STUB: not implemented"; return }

// SetTo sets value to v.
func (o *OptEvent) SetTo(v Event) { _ = "STUB: not implemented"; return }

// Get returns value and boolean that denotes whether value was set.
func (o OptEvent) Get() (v Event, ok bool) { _ = "STUB: not implemented"; return *new(Event), false }

// Or returns value if set, or given parameter if does not.
func (o OptEvent) Or(d Event) Event { _ = "STUB: not implemented"; return *new(Event) }

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString { _ = "STUB: not implemented"; return *new(OptString) }

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool {
	_ = "STUB: not implemented"

	// Reset unsets value.
	return false
}

func (o *OptString) Reset() { _ = "STUB: not implemented"; return }

// SetTo sets value to v.
func (o *OptString) SetTo(v string) { _ = "STUB: not implemented"; return }

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) { _ = "STUB: not implemented"; return "", false }

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string { _ = "STUB: not implemented"; return "" }

type StatusWebhookOK struct {
	Status OptString `json:"status"`
}

// GetStatus returns the value of Status.
func (s *StatusWebhookOK) GetStatus() OptString {
	_ = "STUB: not implemented"

	// SetStatus sets the value of Status.
	return *new(OptString)
}

func (s *StatusWebhookOK) SetStatus(val OptString) {
	_ = "STUB: not implemented"

	// UpdateDeleteOK is response for UpdateDelete operation.
	return
}

type UpdateDeleteOK struct{}

func (*UpdateDeleteOK) updateDeleteRes() {
	_ = "STUB: not implemented"

	// Ref: #/components/schemas/WebhookResponse
	return
}

type WebhookResponse struct {
	ID        uuid.UUID `json:"id"`
	EventType OptString `json:"event_type"`
}

// GetID returns the value of ID.
func (s *WebhookResponse) GetID() uuid.UUID {
	_ = "STUB: not implemented"

	// GetEventType returns the value of EventType.
	return *new(uuid.UUID)
}

func (s *WebhookResponse) GetEventType() OptString {
	_ = "STUB: not implemented"
	return *

	// SetID sets the value of ID.
	new(OptString)
}

func (s *WebhookResponse) SetID(val uuid.UUID) {
	_ = "STUB: not implemented"

	// SetEventType sets the value of EventType.
	return
}

func (s *WebhookResponse) SetEventType(val OptString) { _ = "STUB: not implemented"; return }

func (*WebhookResponse) updateWebhookRes() { _ = "STUB: not implemented"; return }
