// Code generated by ogen, DO NOT EDIT.

package api

// SetFake set fake values.
func (s *Error) SetFake() { _ = "STUB: not implemented"; return }

// SetFake set fake values.
func (s *NewPet) SetFake() { _ = "STUB: not implemented"; return }

// SetFake set fake values.
func (s *OptString) SetFake() { _ = "STUB: not implemented"; return }

// SetFake set fake values.
func (s *Pet) SetFake() { _ = "STUB: not implemented"; return }
