// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/url"
)

func trimTrailingSlashes(u *url.URL) { _ = "STUB: not implemented"; return }

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// AddPet invokes addPet operation.
	//
	// Add a new pet to the store.
	//
	// POST /pet
	AddPet(ctx context.Context, request *Pet) (AddPetRes, error)
	// CreateUser invokes createUser operation.
	//
	// This can only be done by the logged in user.
	//
	// POST /user
	CreateUser(ctx context.Context, request CreateUserReq) (CreateUserRes, error)
	// CreateUsersWithListInput invokes createUsersWithListInput operation.
	//
	// Creates list of users with given input array.
	//
	// POST /user/createWithList
	CreateUsersWithListInput(ctx context.Context, request []User) (CreateUsersWithListInputRes, error)
	// DeleteOrder invokes deleteOrder operation.
	//
	// For valid response try integer IDs with value < 1000. Anything above 1000 or non-integers will
	// generate API errors.
	//
	// DELETE /store/order/{orderId}
	DeleteOrder(ctx context.Context, params DeleteOrderParams) (DeleteOrderRes, error)
	// DeletePet invokes deletePet operation.
	//
	// Delete a pet.
	//
	// DELETE /pet/{petId}
	DeletePet(ctx context.Context, params DeletePetParams) (DeletePetRes, error)
	// DeleteUser invokes deleteUser operation.
	//
	// This can only be done by the logged in user.
	//
	// DELETE /user/{username}
	DeleteUser(ctx context.Context, params DeleteUserParams) (DeleteUserRes, error)
	// FindPetsByStatus invokes findPetsByStatus operation.
	//
	// Multiple status values can be provided with comma separated strings.
	//
	// GET /pet/findByStatus
	FindPetsByStatus(ctx context.Context, params FindPetsByStatusParams) (FindPetsByStatusRes, error)
	// FindPetsByTags invokes findPetsByTags operation.
	//
	// Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
	//
	// GET /pet/findByTags
	FindPetsByTags(ctx context.Context, params FindPetsByTagsParams) (FindPetsByTagsRes, error)
	// GetInventory invokes getInventory operation.
	//
	// Returns a map of status codes to quantities.
	//
	// GET /store/inventory
	GetInventory(ctx context.Context) (GetInventoryRes, error)
	// GetOrderById invokes getOrderById operation.
	//
	// For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
	//
	// GET /store/order/{orderId}
	GetOrderById(ctx context.Context, params GetOrderByIdParams) (GetOrderByIdRes, error)
	// GetPetById invokes getPetById operation.
	//
	// Returns a single pet.
	//
	// GET /pet/{petId}
	GetPetById(ctx context.Context, params GetPetByIdParams) (GetPetByIdRes, error)
	// GetUserByName invokes getUserByName operation.
	//
	// Get user detail based on username.
	//
	// GET /user/{username}
	GetUserByName(ctx context.Context, params GetUserByNameParams) (GetUserByNameRes, error)
	// LoginUser invokes loginUser operation.
	//
	// Log into the system.
	//
	// GET /user/login
	LoginUser(ctx context.Context, params LoginUserParams) (LoginUserRes, error)
	// LogoutUser invokes logoutUser operation.
	//
	// Log user out of the system.
	//
	// GET /user/logout
	LogoutUser(ctx context.Context) (LogoutUserRes, error)
	// PlaceOrder invokes placeOrder operation.
	//
	// Place a new order in the store.
	//
	// POST /store/order
	PlaceOrder(ctx context.Context, request PlaceOrderReq) (PlaceOrderRes, error)
	// UpdatePet invokes updatePet operation.
	//
	// Update an existing pet by Id.
	//
	// PUT /pet
	UpdatePet(ctx context.Context, request *Pet) (UpdatePetRes, error)
	// UpdatePetWithForm invokes updatePetWithForm operation.
	//
	// Updates a pet resource based on the form data.
	//
	// POST /pet/{petId}
	UpdatePetWithForm(ctx context.Context, params UpdatePetWithFormParams) (UpdatePetWithFormRes, error)
	// UpdateUser invokes updateUser operation.
	//
	// This can only be done by the logged in user.
	//
	// PUT /user/{username}
	UpdateUser(ctx context.Context, request UpdateUserReq, params UpdateUserParams) (UpdateUserRes, error)
	// UploadFile invokes uploadFile operation.
	//
	// Upload image of the pet.
	//
	// POST /pet/{petId}/uploadImage
	UploadFile(ctx context.Context, request UploadFileReq, params UploadFileParams) (UploadFileRes, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	sec       SecuritySource
	baseClient
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, sec SecuritySource, opts ...ClientOption) (*Client, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

func (c *Client) requestURL(ctx context.Context) *url.URL { _ = "STUB: not implemented"; return nil }

// AddPet invokes addPet operation.
//
// Add a new pet to the store.
//
// POST /pet
func (c *Client) AddPet(ctx context.Context, request *Pet) (AddPetRes, error) {
	_ = "STUB: not implemented"
	return *new(AddPetRes), nil
}

func (c *Client) sendAddPet(ctx context.Context, request *Pet) (res AddPetRes, err error) {
	_ = "STUB: not implemented"
	return *new(AddPetRes), nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// if NO error

// Skip this security.

// CreateUser invokes createUser operation.
//
// This can only be done by the logged in user.
//
// POST /user
func (c *Client) CreateUser(ctx context.Context, request CreateUserReq) (CreateUserRes, error) {
	_ = "STUB: not implemented"
	return *new(CreateUserRes), nil
}

func (c *Client) sendCreateUser(ctx context.Context, request CreateUserReq) (res CreateUserRes, err error) {
	_ = "STUB: not implemented"
	return *new(CreateUserRes), nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// CreateUsersWithListInput invokes createUsersWithListInput operation.
//
// Creates list of users with given input array.
//
// POST /user/createWithList
func (c *Client) CreateUsersWithListInput(ctx context.Context, request []User) (CreateUsersWithListInputRes, error) {
	_ = "STUB: not implemented"
	return *new(CreateUsersWithListInputRes), nil
}

func (c *Client) sendCreateUsersWithListInput(ctx context.Context, request []User) (res CreateUsersWithListInputRes, err error) {
	_ = "STUB: not implemented"
	return *new(CreateUsersWithListInputRes), nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// DeleteOrder invokes deleteOrder operation.
//
// For valid response try integer IDs with value < 1000. Anything above 1000 or non-integers will
// generate API errors.
//
// DELETE /store/order/{orderId}
func (c *Client) DeleteOrder(ctx context.Context, params DeleteOrderParams) (DeleteOrderRes, error) {
	_ = "STUB: not implemented"
	return *new(DeleteOrderRes), nil
}

func (c *Client) sendDeleteOrder(ctx context.Context, params DeleteOrderParams) (res DeleteOrderRes, err error) {
	_ = "STUB: not implemented"
	return *new(DeleteOrderRes), nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// Encode "orderId" parameter.

// DeletePet invokes deletePet operation.
//
// Delete a pet.
//
// DELETE /pet/{petId}
func (c *Client) DeletePet(ctx context.Context, params DeletePetParams) (DeletePetRes, error) {
	_ = "STUB: not implemented"
	return *new(DeletePetRes), nil
}

func (c *Client) sendDeletePet(ctx context.Context, params DeletePetParams) (res DeletePetRes, err error) {
	_ = "STUB: not implemented"
	return *new(DeletePetRes), nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// Encode "petId" parameter.

// if NO error

// Skip this security.

// DeleteUser invokes deleteUser operation.
//
// This can only be done by the logged in user.
//
// DELETE /user/{username}
func (c *Client) DeleteUser(ctx context.Context, params DeleteUserParams) (DeleteUserRes, error) {
	_ = "STUB: not implemented"
	return *new(DeleteUserRes), nil
}

func (c *Client) sendDeleteUser(ctx context.Context, params DeleteUserParams) (res DeleteUserRes, err error) {
	_ = "STUB: not implemented"
	return *new(DeleteUserRes), nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// Encode "username" parameter.

// FindPetsByStatus invokes findPetsByStatus operation.
//
// Multiple status values can be provided with comma separated strings.
//
// GET /pet/findByStatus
func (c *Client) FindPetsByStatus(ctx context.Context, params FindPetsByStatusParams) (FindPetsByStatusRes, error) {
	_ = "STUB: not implemented"
	return *new(FindPetsByStatusRes), nil
}

func (c *Client) sendFindPetsByStatus(ctx context.Context, params FindPetsByStatusParams) (res FindPetsByStatusRes, err error) {
	_ = "STUB: not implemented"
	return *new(FindPetsByStatusRes), nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// Encode "status" parameter.

// if NO error

// Skip this security.

// FindPetsByTags invokes findPetsByTags operation.
//
// Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
//
// GET /pet/findByTags
func (c *Client) FindPetsByTags(ctx context.Context, params FindPetsByTagsParams) (FindPetsByTagsRes, error) {
	_ = "STUB: not implemented"
	return *new(FindPetsByTagsRes), nil
}

func (c *Client) sendFindPetsByTags(ctx context.Context, params FindPetsByTagsParams) (res FindPetsByTagsRes, err error) {
	_ = "STUB: not implemented"
	return *new(FindPetsByTagsRes), nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// Encode "tags" parameter.

// if NO error

// Skip this security.

// GetInventory invokes getInventory operation.
//
// Returns a map of status codes to quantities.
//
// GET /store/inventory
func (c *Client) GetInventory(ctx context.Context) (GetInventoryRes, error) {
	_ = "STUB: not implemented"
	return *new(GetInventoryRes), nil
}

func (c *Client) sendGetInventory(ctx context.Context) (res GetInventoryRes, err error) {
	_ = "STUB: not implemented"
	return *new(GetInventoryRes), nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// if NO error

// Skip this security.

// GetOrderById invokes getOrderById operation.
//
// For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
//
// GET /store/order/{orderId}
func (c *Client) GetOrderById(ctx context.Context, params GetOrderByIdParams) (GetOrderByIdRes, error) {
	_ = "STUB: not implemented"
	return *new(GetOrderByIdRes), nil
}

func (c *Client) sendGetOrderById(ctx context.Context, params GetOrderByIdParams) (res GetOrderByIdRes, err error) {
	_ = "STUB: not implemented"
	return *new(GetOrderByIdRes), nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// Encode "orderId" parameter.

// GetPetById invokes getPetById operation.
//
// Returns a single pet.
//
// GET /pet/{petId}
func (c *Client) GetPetById(ctx context.Context, params GetPetByIdParams) (GetPetByIdRes, error) {
	_ = "STUB: not implemented"
	return *new(GetPetByIdRes), nil
}

func (c *Client) sendGetPetById(ctx context.Context, params GetPetByIdParams) (res GetPetByIdRes, err error) {
	_ = "STUB: not implemented"
	return *new(GetPetByIdRes), nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// Encode "petId" parameter.

// if NO error

// Skip this security.

// if NO error

// Skip this security.

// GetUserByName invokes getUserByName operation.
//
// Get user detail based on username.
//
// GET /user/{username}
func (c *Client) GetUserByName(ctx context.Context, params GetUserByNameParams) (GetUserByNameRes, error) {
	_ = "STUB: not implemented"
	return *new(GetUserByNameRes), nil
}

func (c *Client) sendGetUserByName(ctx context.Context, params GetUserByNameParams) (res GetUserByNameRes, err error) {
	_ = "STUB: not implemented"
	return *new(GetUserByNameRes), nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// Encode "username" parameter.

// LoginUser invokes loginUser operation.
//
// Log into the system.
//
// GET /user/login
func (c *Client) LoginUser(ctx context.Context, params LoginUserParams) (LoginUserRes, error) {
	_ = "STUB: not implemented"
	return *new(LoginUserRes), nil
}

func (c *Client) sendLoginUser(ctx context.Context, params LoginUserParams) (res LoginUserRes, err error) {
	_ = "STUB: not implemented"
	return *new(LoginUserRes), nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// Encode "username" parameter.

// Encode "password" parameter.

// LogoutUser invokes logoutUser operation.
//
// Log user out of the system.
//
// GET /user/logout
func (c *Client) LogoutUser(ctx context.Context) (LogoutUserRes, error) {
	_ = "STUB: not implemented"
	return *new(LogoutUserRes), nil
}

func (c *Client) sendLogoutUser(ctx context.Context) (res LogoutUserRes, err error) {
	_ = "STUB: not implemented"
	return *new(LogoutUserRes), nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// PlaceOrder invokes placeOrder operation.
//
// Place a new order in the store.
//
// POST /store/order
func (c *Client) PlaceOrder(ctx context.Context, request PlaceOrderReq) (PlaceOrderRes, error) {
	_ = "STUB: not implemented"
	return *new(PlaceOrderRes), nil
}

func (c *Client) sendPlaceOrder(ctx context.Context, request PlaceOrderReq) (res PlaceOrderRes, err error) {
	_ = "STUB: not implemented"
	return *new(PlaceOrderRes), nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// UpdatePet invokes updatePet operation.
//
// Update an existing pet by Id.
//
// PUT /pet
func (c *Client) UpdatePet(ctx context.Context, request *Pet) (UpdatePetRes, error) {
	_ = "STUB: not implemented"
	return *new(UpdatePetRes), nil
}

func (c *Client) sendUpdatePet(ctx context.Context, request *Pet) (res UpdatePetRes, err error) {
	_ = "STUB: not implemented"
	return *new(UpdatePetRes), nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// if NO error

// Skip this security.

// UpdatePetWithForm invokes updatePetWithForm operation.
//
// Updates a pet resource based on the form data.
//
// POST /pet/{petId}
func (c *Client) UpdatePetWithForm(ctx context.Context, params UpdatePetWithFormParams) (UpdatePetWithFormRes, error) {
	_ = "STUB: not implemented"
	return *new(UpdatePetWithFormRes), nil
}

func (c *Client) sendUpdatePetWithForm(ctx context.Context, params UpdatePetWithFormParams) (res UpdatePetWithFormRes, err error) {
	_ = "STUB: not implemented"
	return *new(UpdatePetWithFormRes), nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// Encode "petId" parameter.

// Encode "name" parameter.

// Encode "status" parameter.

// if NO error

// Skip this security.

// UpdateUser invokes updateUser operation.
//
// This can only be done by the logged in user.
//
// PUT /user/{username}
func (c *Client) UpdateUser(ctx context.Context, request UpdateUserReq, params UpdateUserParams) (UpdateUserRes, error) {
	_ = "STUB: not implemented"
	return *new(UpdateUserRes), nil
}

func (c *Client) sendUpdateUser(ctx context.Context, request UpdateUserReq, params UpdateUserParams) (res UpdateUserRes, err error) {
	_ = "STUB: not implemented"
	return *new(UpdateUserRes), nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// Encode "username" parameter.

// UploadFile invokes uploadFile operation.
//
// Upload image of the pet.
//
// POST /pet/{petId}/uploadImage
func (c *Client) UploadFile(ctx context.Context, request UploadFileReq, params UploadFileParams) (UploadFileRes, error) {
	_ = "STUB: not implemented"
	return *new(UploadFileRes), nil
}

func (c *Client) sendUploadFile(ctx context.Context, request UploadFileReq, params UploadFileParams) (res UploadFileRes, err error) {
	_ = "STUB: not implemented"
	return *new(UploadFileRes), nil
}

// Run stopwatch.

// Use floating point division here for higher precision (instead of Millisecond method).

// Increment request counter.

// Start a span for this request.

// Track stage for error reporting.

// Encode "petId" parameter.

// Encode "additionalMetadata" parameter.

// if NO error

// Skip this security.
