// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddPet implements addPet operation.
//
// Add a new pet to the store.
//
// POST /pet
func (UnimplementedHandler) AddPet(ctx context.Context, req *Pet) (r AddPetRes, _ error) {
	_ = "STUB: not implemented"
	return *new(AddPetRes), nil
}

// CreateUser implements createUser operation.
//
// This can only be done by the logged in user.
//
// POST /user
func (UnimplementedHandler) CreateUser(ctx context.Context, req CreateUserReq) (r CreateUserRes, _ error) {
	_ = "STUB: not implemented"
	return *new(CreateUserRes), nil
}

// CreateUsersWithListInput implements createUsersWithListInput operation.
//
// Creates list of users with given input array.
//
// POST /user/createWithList
func (UnimplementedHandler) CreateUsersWithListInput(ctx context.Context, req []User) (r CreateUsersWithListInputRes, _ error) {
	_ = "STUB: not implemented"
	return *new(CreateUsersWithListInputRes), nil
}

// DeleteOrder implements deleteOrder operation.
//
// For valid response try integer IDs with value < 1000. Anything above 1000 or non-integers will
// generate API errors.
//
// DELETE /store/order/{orderId}
func (UnimplementedHandler) DeleteOrder(ctx context.Context, params DeleteOrderParams) (r DeleteOrderRes, _ error) {
	_ = "STUB: not implemented"
	return *new(DeleteOrderRes), nil
}

// DeletePet implements deletePet operation.
//
// Delete a pet.
//
// DELETE /pet/{petId}
func (UnimplementedHandler) DeletePet(ctx context.Context, params DeletePetParams) (r DeletePetRes, _ error) {
	_ = "STUB: not implemented"
	return *new(DeletePetRes), nil
}

// DeleteUser implements deleteUser operation.
//
// This can only be done by the logged in user.
//
// DELETE /user/{username}
func (UnimplementedHandler) DeleteUser(ctx context.Context, params DeleteUserParams) (r DeleteUserRes, _ error) {
	_ = "STUB: not implemented"
	return *new(DeleteUserRes), nil
}

// FindPetsByStatus implements findPetsByStatus operation.
//
// Multiple status values can be provided with comma separated strings.
//
// GET /pet/findByStatus
func (UnimplementedHandler) FindPetsByStatus(ctx context.Context, params FindPetsByStatusParams) (r FindPetsByStatusRes, _ error) {
	_ = "STUB: not implemented"
	return *new(FindPetsByStatusRes), nil
}

// FindPetsByTags implements findPetsByTags operation.
//
// Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
//
// GET /pet/findByTags
func (UnimplementedHandler) FindPetsByTags(ctx context.Context, params FindPetsByTagsParams) (r FindPetsByTagsRes, _ error) {
	_ = "STUB: not implemented"
	return *new(FindPetsByTagsRes), nil
}

// GetInventory implements getInventory operation.
//
// Returns a map of status codes to quantities.
//
// GET /store/inventory
func (UnimplementedHandler) GetInventory(ctx context.Context) (r GetInventoryRes, _ error) {
	_ = "STUB: not implemented"
	return *new(GetInventoryRes), nil
}

// GetOrderById implements getOrderById operation.
//
// For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
//
// GET /store/order/{orderId}
func (UnimplementedHandler) GetOrderById(ctx context.Context, params GetOrderByIdParams) (r GetOrderByIdRes, _ error) {
	_ = "STUB: not implemented"
	return *new(GetOrderByIdRes), nil
}

// GetPetById implements getPetById operation.
//
// Returns a single pet.
//
// GET /pet/{petId}
func (UnimplementedHandler) GetPetById(ctx context.Context, params GetPetByIdParams) (r GetPetByIdRes, _ error) {
	_ = "STUB: not implemented"
	return *new(GetPetByIdRes), nil
}

// GetUserByName implements getUserByName operation.
//
// Get user detail based on username.
//
// GET /user/{username}
func (UnimplementedHandler) GetUserByName(ctx context.Context, params GetUserByNameParams) (r GetUserByNameRes, _ error) {
	_ = "STUB: not implemented"
	return *new(GetUserByNameRes), nil
}

// LoginUser implements loginUser operation.
//
// Log into the system.
//
// GET /user/login
func (UnimplementedHandler) LoginUser(ctx context.Context, params LoginUserParams) (r LoginUserRes, _ error) {
	_ = "STUB: not implemented"
	return *new(LoginUserRes), nil
}

// LogoutUser implements logoutUser operation.
//
// Log user out of the system.
//
// GET /user/logout
func (UnimplementedHandler) LogoutUser(ctx context.Context) (r LogoutUserRes, _ error) {
	_ = "STUB: not implemented"
	return *new(LogoutUserRes), nil
}

// PlaceOrder implements placeOrder operation.
//
// Place a new order in the store.
//
// POST /store/order
func (UnimplementedHandler) PlaceOrder(ctx context.Context, req PlaceOrderReq) (r PlaceOrderRes, _ error) {
	_ = "STUB: not implemented"
	return *new(PlaceOrderRes), nil
}

// UpdatePet implements updatePet operation.
//
// Update an existing pet by Id.
//
// PUT /pet
func (UnimplementedHandler) UpdatePet(ctx context.Context, req *Pet) (r UpdatePetRes, _ error) {
	_ = "STUB: not implemented"
	return *new(UpdatePetRes), nil
}

// UpdatePetWithForm implements updatePetWithForm operation.
//
// Updates a pet resource based on the form data.
//
// POST /pet/{petId}
func (UnimplementedHandler) UpdatePetWithForm(ctx context.Context, params UpdatePetWithFormParams) (r UpdatePetWithFormRes, _ error) {
	_ = "STUB: not implemented"
	return *new(UpdatePetWithFormRes), nil
}

// UpdateUser implements updateUser operation.
//
// This can only be done by the logged in user.
//
// PUT /user/{username}
func (UnimplementedHandler) UpdateUser(ctx context.Context, req UpdateUserReq, params UpdateUserParams) (r UpdateUserRes, _ error) {
	_ = "STUB: not implemented"
	return *new(UpdateUserRes), nil
}

// UploadFile implements uploadFile operation.
//
// Upload image of the pet.
//
// POST /pet/{petId}/uploadImage
func (UnimplementedHandler) UploadFile(ctx context.Context, req UploadFileReq, params UploadFileParams) (r UploadFileRes, _ error) {
	_ = "STUB: not implemented"
	return *new(UploadFileRes), nil
}
